<a href="https://colab.research.google.com/github/RobsonGFerrarezi/ManipulacaoDados_Parte4/blob/main/manipulacao_de_dados_aluno_parte4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a rel="license" href="https://faculdadesalvadorarena.org.br/"><img alt="FESA" style="border-width:0" src="https://faculdadesalvadorarena.org.br/wp-content/uploads/2022/07/logo_fesa.png" /></a><br />
**FESA - Eletiva II (2025.1)** <br/>

Aluno(a): Robson Guilherme Ferrarezi <br/>
Data: 12/04/2025 <br/>

In [ ]:
# pacotes usados neste notebook
import pandas as pd

#Manipulação de Dados com Pandas

##1. Manipulação Básica de Datasets

**Dataset**: Gas Prices in Brazil: https://www.kaggle.com/matheusfreitag/gas-prices-in-brazil <br/>

Este dataset contém os **registros dos preços médios semanais dos combustíveis do Brasil entre os anos de 2004 e 2021**. <br/>
Cada *amostra (registro/linha/observação)* consiste em um registro de preço aferido para um dado tipo de combustível em uma dada localidade do Brasil. <br/>
Alguns dos principais *atributos* (colunas) do dataset são: 'ESTADO', 'PRODUTO', 'NÚMERO DE POSTOS PESQUISADOS', 'PREÇO MÉDIO REVENDA'.

### 1.1. Importando o Dataset
Para carregar um dataset no formato tsv, basta utilizar a função `read_csv` do pandas. Por padrão, ela considera _','_ como separador.

In [ ]:
!wget --no-check-certificate --content-disposition 'https://raw.githubusercontent.com/RobsonGFerrarezi/ManipulacaoDados_Parte4/refs/heads/main/2004-2021.tsv'

--2025-04-12 13:18:14--  https://raw.githubusercontent.com/RobsonGFerrarezi/ManipulacaoDados_Parte4/refs/heads/main/2004-2021.tsv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15640047 (15M) [text/plain]
Saving to: ‘2004-2021.tsv.1’

2004-2021.tsv.1     100%[===================>]  14.92M  32.0MB/s    in 0.5s    

2025-04-12 13:18:15 (32.0 MB/s) - ‘2004-2021.tsv.1’ saved [15640047/15640047]



In [ ]:
df = pd.read_csv('2004-2021.tsv')

In [ ]:
df

DATA INICIAL\tDATA FINAL\tREGIÃO\tESTADO\tPRODUTO\tNÚMERO DE POSTOS PESQUISADOS\tUNIDADE DE MEDIDA\tPREÇO MÉDIO REVENDA\tDESVIO PADRÃO REVENDA\tPREÇO MÍNIMO REVENDA\tPREÇO MÁXIMO REVENDA\tMARGEM MÉDIA REVENDA\tCOEF DE VARIAÇÃO REVENDA\tPREÇO MÉDIO DISTRIBUIÇÃO\tDESVIO PADRÃO DISTRIBUIÇÃO\tPREÇO MÍNIMO DISTRIBUIÇÃO\tPREÇO MÁXIMO DISTRIBUIÇÃO\tCOEF DE VARIAÇÃO DISTRIBUIÇÃO
0       2004-05-09\t2004-05-15\tCENTRO OESTE\tDISTRITO...                                                                                                                                                                                                                                                                                                                                   
1       2004-05-09\t2004-05-15\tCENTRO OESTE\tGOIAS\tE...                                                                                                                                                                                                                                                                                                                                   
2       2004-05-09\t2004-05-15\tCENTRO OESTE\tMATO GRO...                                                                                                                                                                                                                                                                                                                                   
3       2004-05-09\t2004-05-15\tCENTRO OESTE\tMATO GRO...                                                                                                                                                                                                                                                                                                                                   
4       2004-05-09\t2004-05-15\tNORDESTE\tALAGOAS\tETA...                                                                                                                                                                                                                                                                                                                                   
...                                                   ...                                                                                                                                                                                                                                                                                                                                   
120818  2021-04-25\t2021-05-01\tNORTE\tRORAIMA\tOLEO D...                                                                                                                                                                                                                                                                                                                                   
120819  2021-04-25\t2021-05-01\tSUL\tSANTA CATARINA\tO...                                                                                                                                                                                                                                                                                                                                   
120820  2021-04-25\t2021-05-01\tSUDESTE\tSAO PAULO\tOL...                                                                                                                                                                                                                                                                                                                                   
120821  2021-04-25\t2021-05-01\tNORDESTE\tSERGIPE\tOLE...                                                                                                                                            

O dataset não foi carregado corretamente pois o separador utilizado seu arquivo CSV era '\t' (tab) e não a ','. <br/>
Vamos então carregá-lo corretamente:

In [ ]:
# carregando o dataset corretamente ==> neste caso, usa o separador '\t' (tab)
df = pd.read_csv('/content/2004-2021.tsv', sep='\t')

In [ ]:
df

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
...             ...         ...           ...                 ...   
120818   2021-04-25  2021-05-01         NORTE             RORAIMA   
120819   2021-04-25  2021-05-01           SUL      SANTA CATARINA   
120820   2021-04-25  2021-05-01       SUDESTE           SAO PAULO   
120821   2021-04-25  2021-05-01      NORDESTE             SERGIPE   
120822   2021-04-25  2021-05-01         NORTE           TOCANTINS   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
120818   OLEO DIESEL S10                            12              R$/l   
120819   OLEO DIESEL S10                           100              R$/l   
120820   OLEO DIESEL S10                           886              R$/l   
120821   OLEO DIESEL S10                            33              R$/l   
120822   OLEO DIESEL S10                            18              R$/l   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                     1.288                  0.016                 1.190   
1                     1.162                  0.114                 0.890   
2                     1.389                  0.097                 1.180   
3                     1.262                  0.070                 1.090   
4                     1.181                  0.078                 1.050   
...                     ...                    ...                   ...   
120818                4.582                  0.056                 4.510   
120819                4.141                  0.187                 3.838   
120820                4.246                  0.216                 3.769   
120821                4.464                  0.205                 4.190   
120822                4.352                  0.156                 4.199   

        PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                      1.350                0.463                     0.012   
1                      1.449                0.399                     0.098   
2                      1.760                0.419                     0.070   
3                      1.509                0.432                     0.055   
4                      1.400                 0.24                     0.066   
...                      ...                  ...                       ...   
120818                 4.690             -99999.0                     0.012   
120819                 4.739             -99999.0                     0.045   
120820                 5.199             -99999.0                     0.051   
120821                 4.699             -99999.0                     0.046   
120822                 4.699             -99999.0                     0.036   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                         0.825                       0.11   
1                         0.763                      0.088   
2                          0.97                      0.095   
3                          0.83                      0.119   
4                         0.941                      0.077   
...                         ...

### 1.2. Exibindo as primeiras linhas do Dataset
A função `.head()` exibe as 5 primeiras linhas do dataset/tabela/Data Frame.

In [ ]:
df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                1.288                  0.016                  1.19   
1                1.162                  0.114                  0.89   
2                1.389                  0.097                  1.18   
3                1.262                  0.070                  1.09   
4                1.181                  0.078                  1.05   

   PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                 1.350                0.463                     0.012   
1                 1.449                0.399                     0.098   
2                 1.760                0.419                     0.070   
3                 1.509                0.432                     0.055   
4                 1.400                 0.24                     0.066   

  PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                    0.825                       0.11   
1                    0.763                      0.088   
2                     0.97                      0.095   
3                     0.83                      0.119   
4                    0.941                      0.077   

  PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                    0.4201                    0.9666   
1                    0.5013                      1.05   
2                    0.5614                     1.161   
3                    0.5991                   1.22242   
4                    0.7441                    1.0317   

  COEF DE VARIAÇÃO DISTRIBUIÇÃO  
0                         0.133  
1                         0.115  
2                         0.098  
3                         0.143  
4                         0.082

In [ ]:
# exibe as 10 primeiras linhas do dataframe
df.head(10)

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
5   2004-05-09  2004-05-15      NORDESTE               BAHIA   
6   2004-05-09  2004-05-15      NORDESTE               CEARA   
7   2004-05-09  2004-05-15      NORDESTE            MARANHAO   
8   2004-05-09  2004-05-15      NORDESTE             PARAIBA   
9   2004-05-09  2004-05-15      NORDESTE          PERNAMBUCO   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   
5  ETANOL HIDRATADO                           408              R$/l   
6  ETANOL HIDRATADO                           278              R$/l   
7  ETANOL HIDRATADO                           105              R$/l   
8  ETANOL HIDRATADO                           125              R$/l   
9  ETANOL HIDRATADO                           423              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                1.288                  0.016                 1.190   
1                1.162                  0.114                 0.890   
2                1.389                  0.097                 1.180   
3                1.262                  0.070                 1.090   
4                1.181                  0.078                 1.050   
5                1.383                  0.132                 0.999   
6                1.453                  0.218                 1.030   
7                1.631                  0.158                 1.350   
8                1.284                  0.130                 1.100   
9                1.224                  0.141                 0.989   

   PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                 1.350                0.463                     0.012   
1                 1.449                0.399                     0.098   
2                 1.760                0.419                     0.070   
3                 1.509                0.432                     0.055   
4                 1.400                 0.24                     0.066   
5                 2.050                0.426                     0.095   
6                 1.950                0.353                     0.150   
7                 2.000                0.515                     0.097   
8                 1.699                0.353                     0.101   
9                 1.700                0.277                     0.115   

  PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                    0.825                       0.11   
1                    0.763                      0.088   
2                     0.97                      0.095   
3                     0.83                      0.119   
4                    0.941                      0.077   
5                    0.957                      0.128   
6                      1.1                      0.068   
7                    1.116                      0.091   
8                    0.931                      0.072   
9                    0.947                      0.091   

  PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                    0.4201                    0.9666   
1                    0.5013                      1.05   
2                    0.5614                     1.161   
3                    0.5991                   1.22242   
4    

### 1.3 Informações do Dataset e Elementos Chave

### 1.3.1 Informações gerais sobre o Dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   DATA INICIAL                   120823 non-null  object 
 1   DATA FINAL                     120823 non-null  object 
 2   REGIÃO                         120823 non-null  object 
 3   ESTADO                         120823 non-null  object 
 4   PRODUTO                        120823 non-null  object 
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64  
 6   UNIDADE DE MEDIDA              120823 non-null  object 
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object 
 12  COEF DE VARIAÇÃO REVENDA      

Aparentemente, nenhum atributo/coluna possui valores nulos (_null_), uma vez que o número de registros do dataframe e os números de valores _non-null_ é de **120823**. <br/>
Mas, veremos que não é bem assim para esse caso. <br/>
Além disso, note que alguns atributos/colunas, p. ex., 'PREÇO MÉDIO DISTRIBUIÇÃO', possui tipo de dado `object` ao invés de `float`. Esse `object`, no geral, representa strings. Isso parece estranho e suspeito. Veremos se isso é problemático mais pra frente.

### 1.3.2 Data Frame
Todo dataset carregado (dados estruturados) é um `Data Frame`: 'Tabela' bi-dimensional, de tamanho mutável, com dados potencialmente heterogêneos. <br/>

In [ ]:
type(df)

pandas.core.frame.DataFrame

Podemos acessar as **dimensões do Data Frame** (número de linhas x número de colunas) utilizando o atributo `.shape` do Data Frame.

In [ ]:
df.shape

(120823, 18)

In [ ]:
print(f'O DataFrame possui {df.shape[0]} linhas/observações/registros e {df.shape[1]} colunas/atributos/variáveis.')

O DataFrame possui 120823 linhas/observações/registros e 18 colunas/atributos/variáveis.


#### **Criando um DataFrame**

Podemos criar um DataFrame a partir de um _dicionário_, onde cada **chave** possui uma **lista de elementos de igual tamanho**.<br/>
As **chaves** representam as **colunas** e **cada um dos valores de sua lista** representa o **valor da linha** correspondente para aquela coluna.

In [ ]:
personagens_df = pd.DataFrame({
    'Nome': ['Luke Skywalker', 'Yoda', 'Palpatine'],
    'idade': [16, 1000, 70],
    'Peso': [70.5, 15.2, 60.1],
    'Eh jedi': [True, True, False]  # o nome das colunas podem ter espaços
})

In [ ]:
personagens_df

Nome  idade  Peso  Eh jedi
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False

In [ ]:
personagens_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Nome     3 non-null      object 
 1   idade    3 non-null      int64  
 2   Peso     3 non-null      float64
 3   Eh jedi  3 non-null      bool   
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 207.0+ bytes


#### **VEJA MAIS**
Criando um Data Frame a partir de um dicionário: https://www.geeksforgeeks.org/how-to-create-dataframe-from-dictionary-in-python-pandas/

#### **Renomeando as colunas de um DataFrame**
**===>** O método `DataFrame.columns` retorna uma "lista" com os **nomes de todas as colunas** do data frame.

In [ ]:
personagens_df.columns

Index(['Nome', 'idade', 'Peso', 'Eh jedi'], dtype='object')

In [ ]:
type(personagens_df.columns)

pandas.core.indexes.base.Index

In [ ]:
list(personagens_df.columns)

['Nome', 'idade', 'Peso', 'Eh jedi']

<br/>

**===>** Para **renomear colunas** do data frame, utilize o método `DataFrame.rename`, que retorna uma _cópia_ do data frame com as as colunas renomeadas:

In [ ]:
personagens_df

Nome  idade  Peso  Eh jedi
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False

In [ ]:
dic = {'idade': 'Idade', 'Peso': 'Peso (kg)'}
personagens_df_renomeado = personagens_df.rename(columns=dic)

In [ ]:
personagens_df_renomeado

Nome  Idade  Peso (kg)  Eh jedi
0  Luke Skywalker     16       70.5     True
1            Yoda   1000       15.2     True
2       Palpatine     70       60.1    False

In [ ]:
personagens_df

Nome  idade  Peso  Eh jedi
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False

Para renomear o _próprio_ data frame em questão, utilize o parâmetro `inplace=True`:

In [ ]:
personagens_df.rename(columns=dic, inplace=True)

In [ ]:
personagens_df

Nome  Idade  Peso (kg)  Eh jedi
0  Luke Skywalker     16       70.5     True
1            Yoda   1000       15.2     True
2       Palpatine     70       60.1    False

<br/>

**===>** Uma outra forma de **renomear todas as colunas** de um data frame é passar uma _lista_ com os novos nomes das colunas para o atributo `DataFrame.columns`:

In [ ]:
personagens_df.columns

Index(['Nome', 'Idade', 'Peso (kg)', 'Eh jedi'], dtype='object')

In [ ]:
personagens_df.columns = ['NOME', 'IDADE', 'PESO (KG)', 'EH JEDI?']

In [ ]:
personagens_df

NOME  IDADE  PESO (KG)  EH JEDI?
0  Luke Skywalker     16       70.5      True
1            Yoda   1000       15.2      True
2       Palpatine     70       60.1     False

### 1.3.3 Series

Array uni-dimensional com os dados e rótulos de um eixo.

In [ ]:
df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                1.288                  0.016                  1.19   
1                1.162                  0.114                  0.89   
2                1.389                  0.097                  1.18   
3                1.262                  0.070                  1.09   
4                1.181                  0.078                  1.05   

   PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                 1.350                0.463                     0.012   
1                 1.449                0.399                     0.098   
2                 1.760                0.419                     0.070   
3                 1.509                0.432                     0.055   
4                 1.400                 0.24                     0.066   

  PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                    0.825                       0.11   
1                    0.763                      0.088   
2                     0.97                      0.095   
3                     0.83                      0.119   
4                    0.941                      0.077   

  PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                    0.4201                    0.9666   
1                    0.5013                      1.05   
2                    0.5614                     1.161   
3                    0.5991                   1.22242   
4                    0.7441                    1.0317   

  COEF DE VARIAÇÃO DISTRIBUIÇÃO  
0                         0.133  
1                         0.115  
2                         0.098  
3                         0.143  
4                         0.082

In [ ]:
# selecionando uma coluna inteira
df['ESTADO']

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...        
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: object

In [ ]:
# selecionando uma coluna inteira
# esta forma de acesso, só funciona para colunas com nomes sem espaços, acentos, etc
df.ESTADO

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...        
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: object

In [ ]:
type(df['ESTADO'])

pandas.core.series.Series

In [ ]:
# selecionando a observação indexada no índice [1] do dataframe
df.iloc[1]

DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
Name: 1, dtype: object

In [ ]:
type(df.iloc[1])

pandas.core.series.Series

#### **Criando uma Series**

Podemos criar uma Series a partir de uma lista de elementos.

In [ ]:
pd.Series([5.5, 6.0, 9.5])

0    5.5
1    6.0
2    9.5
dtype: float64

Podemos alterar o **nome dos índices** e o **nome da Series** (o que ela representa):

In [ ]:
pd.Series([5.5, 6.0, 9.5], index=['prova 1', 'prova 2', 'projeto'], name='Notas dos Luke Skywalker')

prova 1    5.5
prova 2    6.0
projeto    9.5
Name: Notas dos Luke Skywalker, dtype: float64

#### **VEJA MAIS**
https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html

### 1.3.4 Atribuindo Dados

In [ ]:
df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                1.288                  0.016                  1.19   
1                1.162                  0.114                  0.89   
2                1.389                  0.097                  1.18   
3                1.262                  0.070                  1.09   
4                1.181                  0.078                  1.05   

   PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                 1.350                0.463                     0.012   
1                 1.449                0.399                     0.098   
2                 1.760                0.419                     0.070   
3                 1.509                0.432                     0.055   
4                 1.400                 0.24                     0.066   

  PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                    0.825                       0.11   
1                    0.763                      0.088   
2                     0.97                      0.095   
3                     0.83                      0.119   
4                    0.941                      0.077   

  PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                    0.4201                    0.9666   
1                    0.5013                      1.05   
2                    0.5614                     1.161   
3                    0.5991                   1.22242   
4                    0.7441                    1.0317   

  COEF DE VARIAÇÃO DISTRIBUIÇÃO  
0                         0.133  
1                         0.115  
2                         0.098  
3                         0.143  
4                         0.082

#### 1.3.4.1 Atribuindo constantes

In [ ]:
produto_copy_bkp = df['PRODUTO'].copy()  # retorna uma cópia da coluna 'PRODUTO'
produto_copy_bkp

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...       
120818     OLEO DIESEL S10
120819     OLEO DIESEL S10
120820     OLEO DIESEL S10
120821     OLEO DIESEL S10
120822     OLEO DIESEL S10
Name: PRODUTO, Length: 120823, dtype: object

In [ ]:
df['PRODUTO'] = 'Combustível'  # atribuindo o valor constante 'Combustível' para linha do dataframe na coluna 'PRODUTO'

In [ ]:
df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO      PRODUTO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL  Combustível   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS  Combustível   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO  Combustível   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL  Combustível   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS  Combustível   

   NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
0                           127              R$/l                1.288   
1                           387              R$/l                1.162   
2                           192              R$/l                1.389   
3                           162              R$/l                1.262   
4                           103              R$/l                1.181   

   DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
0                  0.016                  1.19                 1.350   
1                  0.114                  0.89                 1.449   
2                  0.097                  1.18                 1.760   
3                  0.070                  1.09                 1.509   
4                  0.078                  1.05                 1.400   

  MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA PREÇO MÉDIO DISTRIBUIÇÃO  \
0                0.463                     0.012                    0.825   
1                0.399                     0.098                    0.763   
2                0.419                     0.070                     0.97   
3                0.432                     0.055                     0.83   
4                 0.24                     0.066                    0.941   

  DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                       0.11                    0.4201   
1                      0.088                    0.5013   
2                      0.095                    0.5614   
3                      0.119                    0.5991   
4                      0.077                    0.7441   

  PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO  
0                    0.9666                         0.133  
1                      1.05                         0.115  
2                     1.161                         0.098  
3                   1.22242                         0.143  
4                    1.0317                         0.082

#### 1.3.4.2 Atribuindo listas ou series

In [ ]:
nrows, ncols = df.shape
nrows, ncols

(120823, 18)

In [ ]:
novos_produtos = [f'Produto {i}' for i in range(nrows)]
len(novos_produtos)

120823

In [ ]:
# a quantidade de elementos da lista `novos_produtos` é igual ao número de linhas do dataframe
df['PRODUTO'] = novos_produtos

In [ ]:
df

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
...             ...         ...           ...                 ...   
120818   2021-04-25  2021-05-01         NORTE             RORAIMA   
120819   2021-04-25  2021-05-01           SUL      SANTA CATARINA   
120820   2021-04-25  2021-05-01       SUDESTE           SAO PAULO   
120821   2021-04-25  2021-05-01      NORDESTE             SERGIPE   
120822   2021-04-25  2021-05-01         NORTE           TOCANTINS   

               PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0            Produto 0                           127              R$/l   
1            Produto 1                           387              R$/l   
2            Produto 2                           192              R$/l   
3            Produto 3                           162              R$/l   
4            Produto 4                           103              R$/l   
...                ...                           ...               ...   
120818  Produto 120818                            12              R$/l   
120819  Produto 120819                           100              R$/l   
120820  Produto 120820                           886              R$/l   
120821  Produto 120821                            33              R$/l   
120822  Produto 120822                            18              R$/l   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                     1.288                  0.016                 1.190   
1                     1.162                  0.114                 0.890   
2                     1.389                  0.097                 1.180   
3                     1.262                  0.070                 1.090   
4                     1.181                  0.078                 1.050   
...                     ...                    ...                   ...   
120818                4.582                  0.056                 4.510   
120819                4.141                  0.187                 3.838   
120820                4.246                  0.216                 3.769   
120821                4.464                  0.205                 4.190   
120822                4.352                  0.156                 4.199   

        PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                      1.350                0.463                     0.012   
1                      1.449                0.399                     0.098   
2                      1.760                0.419                     0.070   
3                      1.509                0.432                     0.055   
4                      1.400                 0.24                     0.066   
...                      ...                  ...                       ...   
120818                 4.690             -99999.0                     0.012   
120819                 4.739             -99999.0                     0.045   
120820                 5.199             -99999.0                     0.051   
120821                 4.699             -99999.0                     0.046   
120822                 4.699             -99999.0                     0.036   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                         0.825                       0.11   
1                         0.763                      0.088   
2                          0.97                      0.095   
3                          0.83                      0.119   
4                         0.941                      0.077   
...                         ...                        

In [ ]:
# voltando para os produtos originais
df['PRODUTO'] = produto_copy_bkp  # produto_copy_bkp é uma Series

In [ ]:
df

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
...             ...         ...           ...                 ...   
120818   2021-04-25  2021-05-01         NORTE             RORAIMA   
120819   2021-04-25  2021-05-01           SUL      SANTA CATARINA   
120820   2021-04-25  2021-05-01       SUDESTE           SAO PAULO   
120821   2021-04-25  2021-05-01      NORDESTE             SERGIPE   
120822   2021-04-25  2021-05-01         NORTE           TOCANTINS   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
120818   OLEO DIESEL S10                            12              R$/l   
120819   OLEO DIESEL S10                           100              R$/l   
120820   OLEO DIESEL S10                           886              R$/l   
120821   OLEO DIESEL S10                            33              R$/l   
120822   OLEO DIESEL S10                            18              R$/l   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                     1.288                  0.016                 1.190   
1                     1.162                  0.114                 0.890   
2                     1.389                  0.097                 1.180   
3                     1.262                  0.070                 1.090   
4                     1.181                  0.078                 1.050   
...                     ...                    ...                   ...   
120818                4.582                  0.056                 4.510   
120819                4.141                  0.187                 3.838   
120820                4.246                  0.216                 3.769   
120821                4.464                  0.205                 4.190   
120822                4.352                  0.156                 4.199   

        PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                      1.350                0.463                     0.012   
1                      1.449                0.399                     0.098   
2                      1.760                0.419                     0.070   
3                      1.509                0.432                     0.055   
4                      1.400                 0.24                     0.066   
...                      ...                  ...                       ...   
120818                 4.690             -99999.0                     0.012   
120819                 4.739             -99999.0                     0.045   
120820                 5.199             -99999.0                     0.051   
120821                 4.699             -99999.0                     0.046   
120822                 4.699             -99999.0                     0.036   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                         0.825                       0.11   
1                         0.763                      0.088   
2                          0.97                      0.095   
3                          0.83                      0.119   
4                         0.941                      0.077   
...                         ...

#### 1.3.4.3 Criando novas colunas
Para **criar uma nova coluna** em um data frame, basta atribuirmos uma _lista/Series de valores_ a uma **nova 'chave'** do data frame. <br/>

**PS:** A _quantidade de valores_ da lista precisa ser **igual** ao _número de linhas/registros_ do data frame.

In [ ]:
# criando uma coluna a partir de um valor constante/default
# todas as linhas terão o mesmo valor para esta nova coluna
df['coluna sem nocao'] = 'DEFAULT'
df

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
...             ...         ...           ...                 ...   
120818   2021-04-25  2021-05-01         NORTE             RORAIMA   
120819   2021-04-25  2021-05-01           SUL      SANTA CATARINA   
120820   2021-04-25  2021-05-01       SUDESTE           SAO PAULO   
120821   2021-04-25  2021-05-01      NORDESTE             SERGIPE   
120822   2021-04-25  2021-05-01         NORTE           TOCANTINS   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
120818   OLEO DIESEL S10                            12              R$/l   
120819   OLEO DIESEL S10                           100              R$/l   
120820   OLEO DIESEL S10                           886              R$/l   
120821   OLEO DIESEL S10                            33              R$/l   
120822   OLEO DIESEL S10                            18              R$/l   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                     1.288                  0.016                 1.190   
1                     1.162                  0.114                 0.890   
2                     1.389                  0.097                 1.180   
3                     1.262                  0.070                 1.090   
4                     1.181                  0.078                 1.050   
...                     ...                    ...                   ...   
120818                4.582                  0.056                 4.510   
120819                4.141                  0.187                 3.838   
120820                4.246                  0.216                 3.769   
120821                4.464                  0.205                 4.190   
120822                4.352                  0.156                 4.199   

        PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                      1.350                0.463                     0.012   
1                      1.449                0.399                     0.098   
2                      1.760                0.419                     0.070   
3                      1.509                0.432                     0.055   
4                      1.400                 0.24                     0.066   
...                      ...                  ...                       ...   
120818                 4.690             -99999.0                     0.012   
120819                 4.739             -99999.0                     0.045   
120820                 5.199             -99999.0                     0.051   
120821                 4.699             -99999.0                     0.046   
120822                 4.699             -99999.0                     0.036   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                         0.825                       0.11   
1                         0.763                      0.088   
2                          0.97                      0.095   
3                          0.83                      0.119   
4                         0.941                      0.077   
...                         ...

In [ ]:
df['coluna a partir de lista'] = range(df.shape[0])

In [ ]:
df

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
...             ...         ...           ...                 ...   
120818   2021-04-25  2021-05-01         NORTE             RORAIMA   
120819   2021-04-25  2021-05-01           SUL      SANTA CATARINA   
120820   2021-04-25  2021-05-01       SUDESTE           SAO PAULO   
120821   2021-04-25  2021-05-01      NORDESTE             SERGIPE   
120822   2021-04-25  2021-05-01         NORTE           TOCANTINS   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
120818   OLEO DIESEL S10                            12              R$/l   
120819   OLEO DIESEL S10                           100              R$/l   
120820   OLEO DIESEL S10                           886              R$/l   
120821   OLEO DIESEL S10                            33              R$/l   
120822   OLEO DIESEL S10                            18              R$/l   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                     1.288                  0.016                 1.190   
1                     1.162                  0.114                 0.890   
2                     1.389                  0.097                 1.180   
3                     1.262                  0.070                 1.090   
4                     1.181                  0.078                 1.050   
...                     ...                    ...                   ...   
120818                4.582                  0.056                 4.510   
120819                4.141                  0.187                 3.838   
120820                4.246                  0.216                 3.769   
120821                4.464                  0.205                 4.190   
120822                4.352                  0.156                 4.199   

        PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                      1.350                0.463                     0.012   
1                      1.449                0.399                     0.098   
2                      1.760                0.419                     0.070   
3                      1.509                0.432                     0.055   
4                      1.400                 0.24                     0.066   
...                      ...                  ...                       ...   
120818                 4.690             -99999.0                     0.012   
120819                 4.739             -99999.0                     0.045   
120820                 5.199             -99999.0                     0.051   
120821                 4.699             -99999.0                     0.046   
120822                 4.699             -99999.0                     0.036   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                         0.825                       0.11   
1                         0.763                      0.088   
2                          0.97                      0.095   
3                          0.83                      0.119   
4                         0.941                      0.077   
...                         ...

In [ ]:
# não funciona porque a quantidade de elementos da lista (a serem atribuídos a nova coluna) é diferente
# da quantidade de linhas do dataframe
#df['nao funciona'] = [1, 2, 3]

In [ ]:
personagens_df

NOME  IDADE  PESO (KG)  EH JEDI?
0  Luke Skywalker     16       70.5      True
1            Yoda   1000       15.2      True
2       Palpatine     70       60.1     False

In [ ]:
personagens_df['COR DO SABRE DE LUZ'] = ['Azul', 'Verde', 'Vermelho']

In [ ]:
personagens_df

NOME  IDADE  PESO (KG)  EH JEDI? COR DO SABRE DE LUZ
0  Luke Skywalker     16       70.5      True                Azul
1            Yoda   1000       15.2      True               Verde
2       Palpatine     70       60.1     False            Vermelho

<br/>

Outro exemplo:

In [ ]:
df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                1.288                  0.016                  1.19   
1                1.162                  0.114                  0.89   
2                1.389                  0.097                  1.18   
3                1.262                  0.070                  1.09   
4                1.181                  0.078                  1.05   

   PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                 1.350                0.463                     0.012   
1                 1.449                0.399                     0.098   
2                 1.760                0.419                     0.070   
3                 1.509                0.432                     0.055   
4                 1.400                 0.24                     0.066   

  PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                    0.825                       0.11   
1                    0.763                      0.088   
2                     0.97                      0.095   
3                     0.83                      0.119   
4                    0.941                      0.077   

  PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                    0.4201                    0.9666   
1                    0.5013                      1.05   
2                    0.5614                     1.161   
3                    0.5991                   1.22242   
4                    0.7441                    1.0317   

  COEF DE VARIAÇÃO DISTRIBUIÇÃO coluna sem nocao  coluna a partir de lista  
0                         0.133          DEFAULT                         0  
1                         0.115          DEFAULT                         1  
2                         0.098          DEFAULT                         2  
3                         0.143          DEFAULT                         3  
4                         0.082          DEFAULT                         4

In [ ]:

df['PREÇO MÉDIO REVENDA (dólares)'] = df['PREÇO MÉDIO REVENDA'] / 5.75

In [ ]:
df

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
...             ...         ...           ...                 ...   
120818   2021-04-25  2021-05-01         NORTE             RORAIMA   
120819   2021-04-25  2021-05-01           SUL      SANTA CATARINA   
120820   2021-04-25  2021-05-01       SUDESTE           SAO PAULO   
120821   2021-04-25  2021-05-01      NORDESTE             SERGIPE   
120822   2021-04-25  2021-05-01         NORTE           TOCANTINS   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
120818   OLEO DIESEL S10                            12              R$/l   
120819   OLEO DIESEL S10                           100              R$/l   
120820   OLEO DIESEL S10                           886              R$/l   
120821   OLEO DIESEL S10                            33              R$/l   
120822   OLEO DIESEL S10                            18              R$/l   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  ...  \
0                     1.288                  0.016                 1.190  ...   
1                     1.162                  0.114                 0.890  ...   
2                     1.389                  0.097                 1.180  ...   
3                     1.262                  0.070                 1.090  ...   
4                     1.181                  0.078                 1.050  ...   
...                     ...                    ...                   ...  ...   
120818                4.582                  0.056                 4.510  ...   
120819                4.141                  0.187                 3.838  ...   
120820                4.246                  0.216                 3.769  ...   
120821                4.464                  0.205                 4.190  ...   
120822                4.352                  0.156                 4.199  ...   

        MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  \
0                      0.463                    0.012   
1                      0.399                    0.098   
2                      0.419                    0.070   
3                      0.432                    0.055   
4                       0.24                    0.066   
...                      ...                      ...   
120818              -99999.0                    0.012   
120819              -99999.0                    0.045   
120820              -99999.0                    0.051   
120821              -99999.0                    0.046   
120822              -99999.0                    0.036   

        PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                          0.825                       0.11   
1                          0.763                      0.088   
2                           0.97                      0.095   
3                           0.83                      0.119   
4                          0.941                      0.077   
...                          ...                        ...   
120818                  -99999.0                   -99999.0   
120819                  -99999.0                   -99999.0   
120820                  -99999.0        

### 1.3.4 Índices

Todo Data Frame possui **índices**, que não são considerado colunas da tabela. Tais índices são comumente **númericos**, de 0 a num_linhas-1, mas também podem ser **textuais (rótulos/labels)**.

In [ ]:
df

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
...             ...         ...           ...                 ...   
120818   2021-04-25  2021-05-01         NORTE             RORAIMA   
120819   2021-04-25  2021-05-01           SUL      SANTA CATARINA   
120820   2021-04-25  2021-05-01       SUDESTE           SAO PAULO   
120821   2021-04-25  2021-05-01      NORDESTE             SERGIPE   
120822   2021-04-25  2021-05-01         NORTE           TOCANTINS   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
120818   OLEO DIESEL S10                            12              R$/l   
120819   OLEO DIESEL S10                           100              R$/l   
120820   OLEO DIESEL S10                           886              R$/l   
120821   OLEO DIESEL S10                            33              R$/l   
120822   OLEO DIESEL S10                            18              R$/l   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  ...  \
0                     1.288                  0.016                 1.190  ...   
1                     1.162                  0.114                 0.890  ...   
2                     1.389                  0.097                 1.180  ...   
3                     1.262                  0.070                 1.090  ...   
4                     1.181                  0.078                 1.050  ...   
...                     ...                    ...                   ...  ...   
120818                4.582                  0.056                 4.510  ...   
120819                4.141                  0.187                 3.838  ...   
120820                4.246                  0.216                 3.769  ...   
120821                4.464                  0.205                 4.190  ...   
120822                4.352                  0.156                 4.199  ...   

        MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  \
0                      0.463                    0.012   
1                      0.399                    0.098   
2                      0.419                    0.070   
3                      0.432                    0.055   
4                       0.24                    0.066   
...                      ...                      ...   
120818              -99999.0                    0.012   
120819              -99999.0                    0.045   
120820              -99999.0                    0.051   
120821              -99999.0                    0.046   
120822              -99999.0                    0.036   

        PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                          0.825                       0.11   
1                          0.763                      0.088   
2                           0.97                      0.095   
3                           0.83                      0.119   
4                          0.941                      0.077   
...                          ...                        ...   
120818                  -99999.0                   -99999.0   
120819                  -99999.0                   -99999.0   
120820                  -99999.0        

In [ ]:
df.index

RangeIndex(start=0, stop=120823, step=1)

Use `list(data.index)` ou `data.index.to_list()` para converter um RangeIndex para uma python list.

#### **Exemplo de Data Frame com Índices Textuais (labels)**

In [ ]:
pesquisa_de_satisfacao = pd.DataFrame({
    'bom': [50, 21, 100],
    'ruim': [131, 2, 30],
    'pessimo': [30, 20, 1]
}, index=['Xbox One', 'Playstation4', 'Switch'])

In [ ]:
pesquisa_de_satisfacao.head()

bom  ruim  pessimo
Xbox One       50   131       30
Playstation4   21     2       20
Switch        100    30        1

In [ ]:
pesquisa_de_satisfacao.index

Index(['Xbox One', 'Playstation4', 'Switch'], dtype='object')

### 1.4 Selecionando uma ou mais observações (Indexação)

#### **==>  Index-based selection (seleção baseada em Índices)**
Mostrando linhas específicas de um DataFrame:

`iloc`: seleciona elementos do Dataframe, baseado em seu **índice (número)** --> row-first, column-second

**Selecionando uma observação/linha:**

In [ ]:
df

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
...             ...         ...           ...                 ...   
120818   2021-04-25  2021-05-01         NORTE             RORAIMA   
120819   2021-04-25  2021-05-01           SUL      SANTA CATARINA   
120820   2021-04-25  2021-05-01       SUDESTE           SAO PAULO   
120821   2021-04-25  2021-05-01      NORDESTE             SERGIPE   
120822   2021-04-25  2021-05-01         NORTE           TOCANTINS   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
120818   OLEO DIESEL S10                            12              R$/l   
120819   OLEO DIESEL S10                           100              R$/l   
120820   OLEO DIESEL S10                           886              R$/l   
120821   OLEO DIESEL S10                            33              R$/l   
120822   OLEO DIESEL S10                            18              R$/l   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  ...  \
0                     1.288                  0.016                 1.190  ...   
1                     1.162                  0.114                 0.890  ...   
2                     1.389                  0.097                 1.180  ...   
3                     1.262                  0.070                 1.090  ...   
4                     1.181                  0.078                 1.050  ...   
...                     ...                    ...                   ...  ...   
120818                4.582                  0.056                 4.510  ...   
120819                4.141                  0.187                 3.838  ...   
120820                4.246                  0.216                 3.769  ...   
120821                4.464                  0.205                 4.190  ...   
120822                4.352                  0.156                 4.199  ...   

        MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  \
0                      0.463                    0.012   
1                      0.399                    0.098   
2                      0.419                    0.070   
3                      0.432                    0.055   
4                       0.24                    0.066   
...                      ...                      ...   
120818              -99999.0                    0.012   
120819              -99999.0                    0.045   
120820              -99999.0                    0.051   
120821              -99999.0                    0.046   
120822              -99999.0                    0.036   

        PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                          0.825                       0.11   
1                          0.763                      0.088   
2                           0.97                      0.095   
3                           0.83                      0.119   
4                          0.941                      0.077   
...                          ...                        ...   
120818                  -99999.0                   -99999.0   
120819                  -99999.0                   -99999.0   
120820                  -99999.0        

In [ ]:
df.iloc[1]

DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
coluna sem nocao                          DEFAULT
coluna a partir de lista                        1
PREÇO MÉDIO REVENDA (dólares)            0.202087
Name: 1, dtype: object

**Selecionando múltiplias amostras/linhas:**

In [ ]:
# selecionando as linhas de índice de 0 a 5 (incluso)
df.iloc[:6]

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
5   2004-05-09  2004-05-15      NORDESTE               BAHIA   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   
5  ETANOL HIDRATADO                           408              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  ...  \
0                1.288                  0.016                 1.190  ...   
1                1.162                  0.114                 0.890  ...   
2                1.389                  0.097                 1.180  ...   
3                1.262                  0.070                 1.090  ...   
4                1.181                  0.078                 1.050  ...   
5                1.383                  0.132                 0.999  ...   

   MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
0                 0.463                    0.012                     0.825   
1                 0.399                    0.098                     0.763   
2                 0.419                    0.070                      0.97   
3                 0.432                    0.055                      0.83   
4                  0.24                    0.066                     0.941   
5                 0.426                    0.095                     0.957   

  DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                       0.11                    0.4201   
1                      0.088                    0.5013   
2                      0.095                    0.5614   
3                      0.119                    0.5991   
4                      0.077                    0.7441   
5                      0.128                    0.5686   

  PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO coluna sem nocao  \
0                    0.9666                         0.133          DEFAULT   
1                      1.05                         0.115          DEFAULT   
2                     1.161                         0.098          DEFAULT   
3                   1.22242                         0.143          DEFAULT   
4                    1.0317                         0.082          DEFAULT   
5                      1.35                         0.134          DEFAULT   

  coluna a partir de lista  PREÇO MÉDIO REVENDA (dólares)  
0                        0                       0.224000  
1                        1                       0.202087  
2                        2                       0.241565  
3                        3                       0.219478  
4                        4                       0.205391  
5                        5                       0.240522  

[6 rows x 21 columns]

In [ ]:
# selecionando as linhas de índice 10 a 15 (incluso)
df.iloc[10:16]

DATA INICIAL  DATA FINAL    REGIÃO               ESTADO           PRODUTO  \
10   2004-05-09  2004-05-15  NORDESTE                PIAUI  ETANOL HIDRATADO   
11   2004-05-09  2004-05-15  NORDESTE  RIO GRANDE DO NORTE  ETANOL HIDRATADO   
12   2004-05-09  2004-05-15  NORDESTE              SERGIPE  ETANOL HIDRATADO   
13   2004-05-09  2004-05-15     NORTE                 ACRE  ETANOL HIDRATADO   
14   2004-05-09  2004-05-15     NORTE                AMAPA  ETANOL HIDRATADO   
15   2004-05-09  2004-05-15     NORTE             AMAZONAS  ETANOL HIDRATADO   

    NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
10                            89              R$/l                1.573   
11                           131              R$/l                1.276   
12                            57              R$/l                1.301   
13                            33              R$/l                1.805   
14                            15              R$/l                1.785   
15                            53              R$/l                1.578   

    DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  ...  MARGEM MÉDIA REVENDA  \
10                  0.134                  1.40  ...                 0.494   
11                  0.116                  1.09  ...                 0.332   
12                  0.109                  1.15  ...                 0.321   
13                  0.134                  1.50  ...                 0.689   
14                  0.035                  1.74  ...                 0.412   
15                  0.123                  1.28  ...                 0.441   

   COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
10                    0.085                     1.079   
11                    0.091                     0.944   
12                    0.084                      0.98   
13                    0.074                     1.116   
14                    0.020                     1.373   
15                    0.078                     1.137   

   DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
10                      0.078                    0.8857   
11                      0.078                    0.7119   
12                      0.052                    0.8267   
13                      0.171                     0.767   
14                      0.167                    0.8339   
15                      0.068                    0.9515   

   PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO coluna sem nocao  \
10                    1.2499                         0.072          DEFAULT   
11                    1.1386                         0.083          DEFAULT   
12                    1.1059                         0.053          DEFAULT   
13                    1.2992                         0.153          DEFAULT   
14                    1.4912                         0.122          DEFAULT   
15                    1.2109                          0.06          DEFAULT   

   coluna a partir de lista  PREÇO MÉDIO REVENDA (dólares)  
10                       10                       0.273565  
11                       11                       0.221913  
12                       12                       0.226261  
13                       13                       0.313913  
14                       14                       0.310435  
15                       15                       0.274435  

[6 rows x 21 columns]

In [ ]:
# selecionando as linhas de índice 1, 5, 10 e 15
df.iloc[[1, 5, 10, 15]]

DATA INICIAL  DATA FINAL        REGIÃO    ESTADO           PRODUTO  \
1    2004-05-09  2004-05-15  CENTRO OESTE     GOIAS  ETANOL HIDRATADO   
5    2004-05-09  2004-05-15      NORDESTE     BAHIA  ETANOL HIDRATADO   
10   2004-05-09  2004-05-15      NORDESTE     PIAUI  ETANOL HIDRATADO   
15   2004-05-09  2004-05-15         NORTE  AMAZONAS  ETANOL HIDRATADO   

    NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
1                            387              R$/l                1.162   
5                            408              R$/l                1.383   
10                            89              R$/l                1.573   
15                            53              R$/l                1.578   

    DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  ...  MARGEM MÉDIA REVENDA  \
1                   0.114                 0.890  ...                 0.399   
5                   0.132                 0.999  ...                 0.426   
10                  0.134                 1.400  ...                 0.494   
15                  0.123                 1.280  ...                 0.441   

   COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
1                     0.098                     0.763   
5                     0.095                     0.957   
10                    0.085                     1.079   
15                    0.078                     1.137   

   DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
1                       0.088                    0.5013   
5                       0.128                    0.5686   
10                      0.078                    0.8857   
15                      0.068                    0.9515   

   PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO coluna sem nocao  \
1                       1.05                         0.115          DEFAULT   
5                       1.35                         0.134          DEFAULT   
10                    1.2499                         0.072          DEFAULT   
15                    1.2109                          0.06          DEFAULT   

   coluna a partir de lista  PREÇO MÉDIO REVENDA (dólares)  
1                         1                       0.202087  
5                         5                       0.240522  
10                       10                       0.273565  
15                       15                       0.274435  

[4 rows x 21 columns]

In [ ]:
# selecionando as linhas de índice 5, 1, 15 e 10
df.iloc[[5, 1, 15, 10]]

DATA INICIAL  DATA FINAL        REGIÃO    ESTADO           PRODUTO  \
5    2004-05-09  2004-05-15      NORDESTE     BAHIA  ETANOL HIDRATADO   
1    2004-05-09  2004-05-15  CENTRO OESTE     GOIAS  ETANOL HIDRATADO   
15   2004-05-09  2004-05-15         NORTE  AMAZONAS  ETANOL HIDRATADO   
10   2004-05-09  2004-05-15      NORDESTE     PIAUI  ETANOL HIDRATADO   

    NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
5                            408              R$/l                1.383   
1                            387              R$/l                1.162   
15                            53              R$/l                1.578   
10                            89              R$/l                1.573   

    DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  ...  MARGEM MÉDIA REVENDA  \
5                   0.132                 0.999  ...                 0.426   
1                   0.114                 0.890  ...                 0.399   
15                  0.123                 1.280  ...                 0.441   
10                  0.134                 1.400  ...                 0.494   

   COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
5                     0.095                     0.957   
1                     0.098                     0.763   
15                    0.078                     1.137   
10                    0.085                     1.079   

   DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
5                       0.128                    0.5686   
1                       0.088                    0.5013   
15                      0.068                    0.9515   
10                      0.078                    0.8857   

   PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO coluna sem nocao  \
5                       1.35                         0.134          DEFAULT   
1                       1.05                         0.115          DEFAULT   
15                    1.2109                          0.06          DEFAULT   
10                    1.2499                         0.072          DEFAULT   

   coluna a partir de lista  PREÇO MÉDIO REVENDA (dólares)  
5                         5                       0.240522  
1                         1                       0.202087  
15                       15                       0.274435  
10                       10                       0.273565  

[4 rows x 21 columns]

In [ ]:
df.iloc[5, 5]

np.int64(408)

In [ ]:
# e assim por diante!

#### **==>  Label-based selection (seleção baseadas em Rótulos)**

`loc`: seleciona elementos do Dataframe, baseado em seus **rótulos** --> row-first, column-second

In [ ]:
pesquisa_de_satisfacao

bom  ruim  pessimo
Xbox One       50   131       30
Playstation4   21     2       20
Switch        100    30        1

In [ ]:
# retorna a linha cujo rótulo é 'Xbox One'
pesquisa_de_satisfacao.loc['Xbox One']

bom         50
ruim       131
pessimo     30
Name: Xbox One, dtype: int64

In [ ]:
# retorna a linha de índice 0 (implícito)
pesquisa_de_satisfacao.iloc[0]

bom         50
ruim       131
pessimo     30
Name: Xbox One, dtype: int64

In [ ]:
pesquisa_de_satisfacao.iloc[1,1]

np.int64(2)

In [ ]:
# NÃO FUNCIONA
#pesquisa_de_satisfacao.iloc['Xbox One']

In [ ]:
# NÃO FUNCIONA
#pesquisa_de_satisfacao.loc[0]

In [ ]:
pesquisa_de_satisfacao.loc['Playstation4','ruim']

np.int64(2)

In [ ]:
# seleção direta das colunas
pesquisa_de_satisfacao[['bom', 'pessimo']]

bom  pessimo
Xbox One       50       30
Playstation4   21       20
Switch        100        1

In [ ]:
# outra forma de selecionar colunas com o .loc
pesquisa_de_satisfacao.loc[:, ['bom', 'pessimo']]

bom  pessimo
Xbox One       50       30
Playstation4   21       20
Switch        100        1

### 1.5 Selecionando um ou mais atributos (colunas)

In [ ]:
df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  ...  \
0                1.288                  0.016                  1.19  ...   
1                1.162                  0.114                  0.89  ...   
2                1.389                  0.097                  1.18  ...   
3                1.262                  0.070                  1.09  ...   
4                1.181                  0.078                  1.05  ...   

   MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
0                 0.463                    0.012                     0.825   
1                 0.399                    0.098                     0.763   
2                 0.419                    0.070                      0.97   
3                 0.432                    0.055                      0.83   
4                  0.24                    0.066                     0.941   

  DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                       0.11                    0.4201   
1                      0.088                    0.5013   
2                      0.095                    0.5614   
3                      0.119                    0.5991   
4                      0.077                    0.7441   

  PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO coluna sem nocao  \
0                    0.9666                         0.133          DEFAULT   
1                      1.05                         0.115          DEFAULT   
2                     1.161                         0.098          DEFAULT   
3                   1.22242                         0.143          DEFAULT   
4                    1.0317                         0.082          DEFAULT   

  coluna a partir de lista  PREÇO MÉDIO REVENDA (dólares)  
0                        0                       0.224000  
1                        1                       0.202087  
2                        2                       0.241565  
3                        3                       0.219478  
4                        4                       0.205391  

[5 rows x 21 columns]

In [ ]:
# forma 1
df['ESTADO']

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...        
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: object

In [ ]:
# forma 2, porém
# só funciona se o NOME_DA_COLUNA não possuir espaços, acentuação, etc
df.ESTADO

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...        
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: object

In [ ]:
# forma 3
df.loc[:, 'ESTADO']

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...        
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: object

### Exercício: Como selecionar a coluna **DATA INICIAL**?

In [ ]:
df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  ...  \
0                1.288                  0.016                  1.19  ...   
1                1.162                  0.114                  0.89  ...   
2                1.389                  0.097                  1.18  ...   
3                1.262                  0.070                  1.09  ...   
4                1.181                  0.078                  1.05  ...   

   MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
0                 0.463                    0.012                     0.825   
1                 0.399                    0.098                     0.763   
2                 0.419                    0.070                      0.97   
3                 0.432                    0.055                      0.83   
4                  0.24                    0.066                     0.941   

  DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                       0.11                    0.4201   
1                      0.088                    0.5013   
2                      0.095                    0.5614   
3                      0.119                    0.5991   
4                      0.077                    0.7441   

  PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO coluna sem nocao  \
0                    0.9666                         0.133          DEFAULT   
1                      1.05                         0.115          DEFAULT   
2                     1.161                         0.098          DEFAULT   
3                   1.22242                         0.143          DEFAULT   
4                    1.0317                         0.082          DEFAULT   

  coluna a partir de lista  PREÇO MÉDIO REVENDA (dólares)  
0                        0                       0.224000  
1                        1                       0.202087  
2                        2                       0.241565  
3                        3                       0.219478  
4                        4                       0.205391  

[5 rows x 21 columns]

In [ ]:
df['DATA INICIAL']

0         2004-05-09
1         2004-05-09
2         2004-05-09
3         2004-05-09
4         2004-05-09
             ...    
120818    2021-04-25
120819    2021-04-25
120820    2021-04-25
120821    2021-04-25
120822    2021-04-25
Name: DATA INICIAL, Length: 120823, dtype: object

In [ ]:
df.loc[:, 'DATA INICIAL']

0         2004-05-09
1         2004-05-09
2         2004-05-09
3         2004-05-09
4         2004-05-09
             ...    
120818    2021-04-25
120819    2021-04-25
120820    2021-04-25
120821    2021-04-25
120822    2021-04-25
Name: DATA INICIAL, Length: 120823, dtype: object

In [ ]:
#df.DATA INICIAL # não funciona

### 1.6 Removendo um Atributo (Coluna) do Data Frame

In [ ]:
df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  ...  \
0                1.288                  0.016                  1.19  ...   
1                1.162                  0.114                  0.89  ...   
2                1.389                  0.097                  1.18  ...   
3                1.262                  0.070                  1.09  ...   
4                1.181                  0.078                  1.05  ...   

   MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
0                 0.463                    0.012                     0.825   
1                 0.399                    0.098                     0.763   
2                 0.419                    0.070                      0.97   
3                 0.432                    0.055                      0.83   
4                  0.24                    0.066                     0.941   

  DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                       0.11                    0.4201   
1                      0.088                    0.5013   
2                      0.095                    0.5614   
3                      0.119                    0.5991   
4                      0.077                    0.7441   

  PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO coluna sem nocao  \
0                    0.9666                         0.133          DEFAULT   
1                      1.05                         0.115          DEFAULT   
2                     1.161                         0.098          DEFAULT   
3                   1.22242                         0.143          DEFAULT   
4                    1.0317                         0.082          DEFAULT   

  coluna a partir de lista  PREÇO MÉDIO REVENDA (dólares)  
0                        0                       0.224000  
1                        1                       0.202087  
2                        2                       0.241565  
3                        3                       0.219478  
4                        4                       0.205391  

[5 rows x 21 columns]

In [ ]:
del df['coluna sem nocao']

In [ ]:
df

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
...             ...         ...           ...                 ...   
120818   2021-04-25  2021-05-01         NORTE             RORAIMA   
120819   2021-04-25  2021-05-01           SUL      SANTA CATARINA   
120820   2021-04-25  2021-05-01       SUDESTE           SAO PAULO   
120821   2021-04-25  2021-05-01      NORDESTE             SERGIPE   
120822   2021-04-25  2021-05-01         NORTE           TOCANTINS   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
120818   OLEO DIESEL S10                            12              R$/l   
120819   OLEO DIESEL S10                           100              R$/l   
120820   OLEO DIESEL S10                           886              R$/l   
120821   OLEO DIESEL S10                            33              R$/l   
120822   OLEO DIESEL S10                            18              R$/l   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                     1.288                  0.016                 1.190   
1                     1.162                  0.114                 0.890   
2                     1.389                  0.097                 1.180   
3                     1.262                  0.070                 1.090   
4                     1.181                  0.078                 1.050   
...                     ...                    ...                   ...   
120818                4.582                  0.056                 4.510   
120819                4.141                  0.187                 3.838   
120820                4.246                  0.216                 3.769   
120821                4.464                  0.205                 4.190   
120822                4.352                  0.156                 4.199   

        PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                      1.350                0.463                     0.012   
1                      1.449                0.399                     0.098   
2                      1.760                0.419                     0.070   
3                      1.509                0.432                     0.055   
4                      1.400                 0.24                     0.066   
...                      ...                  ...                       ...   
120818                 4.690             -99999.0                     0.012   
120819                 4.739             -99999.0                     0.045   
120820                 5.199             -99999.0                     0.051   
120821                 4.699             -99999.0                     0.046   
120822                 4.699             -99999.0                     0.036   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                         0.825                       0.11   
1                         0.763                      0.088   
2                          0.97                      0.095   
3                          0.83                      0.119   
4                         0.941                      0.077   
...                         ...

### Exercício: Como remover as colunas **coluna a partir de lista** e **PREÇO MÉDIO REVENDA (dólares)**?

In [ ]:
# del não funciona para excluir múltiplas colunas. Veremos como fazer isso mais para frente
#del df[['coluna a partir de lista', 'PREÇO MÉDIO REVENDA (dólares)']]

In [ ]:
del df['coluna a partir de lista']
del df['PREÇO MÉDIO REVENDA (dólares)']

### 1.7 Salvando um Data Frame

Para salvarmos um Data Frame para um **arquivo CSV**, basta usarmos o método `.to_csv`. <br/>
Por padrão, esse método **salva os índices da tabela como uma coluna no CSV**.<br/>
Como no geral tais índices são números de 0 a n-1, não há necessidade para isso.<br/>
Desta forma, utilize o parâmetro: `index=False`.

Por padrão, o método utilizará a ',' como separador das colunas. Caso queira alterá-lo, utilize o parâmetro `sep`.

In [ ]:
df.to_csv('/content/2004-2021_preprocessado.csv', index=False)

In [ ]:
# importando o dataframe salvo na célula anterior
meu_df = pd.read_csv('/content/2004-2021_preprocessado.csv')

In [ ]:
meu_df

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
...             ...         ...           ...                 ...   
120818   2021-04-25  2021-05-01         NORTE             RORAIMA   
120819   2021-04-25  2021-05-01           SUL      SANTA CATARINA   
120820   2021-04-25  2021-05-01       SUDESTE           SAO PAULO   
120821   2021-04-25  2021-05-01      NORDESTE             SERGIPE   
120822   2021-04-25  2021-05-01         NORTE           TOCANTINS   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
120818   OLEO DIESEL S10                            12              R$/l   
120819   OLEO DIESEL S10                           100              R$/l   
120820   OLEO DIESEL S10                           886              R$/l   
120821   OLEO DIESEL S10                            33              R$/l   
120822   OLEO DIESEL S10                            18              R$/l   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                     1.288                  0.016                 1.190   
1                     1.162                  0.114                 0.890   
2                     1.389                  0.097                 1.180   
3                     1.262                  0.070                 1.090   
4                     1.181                  0.078                 1.050   
...                     ...                    ...                   ...   
120818                4.582                  0.056                 4.510   
120819                4.141                  0.187                 3.838   
120820                4.246                  0.216                 3.769   
120821                4.464                  0.205                 4.190   
120822                4.352                  0.156                 4.199   

        PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                      1.350                0.463                     0.012   
1                      1.449                0.399                     0.098   
2                      1.760                0.419                     0.070   
3                      1.509                0.432                     0.055   
4                      1.400                 0.24                     0.066   
...                      ...                  ...                       ...   
120818                 4.690             -99999.0                     0.012   
120819                 4.739             -99999.0                     0.045   
120820                 5.199             -99999.0                     0.051   
120821                 4.699             -99999.0                     0.046   
120822                 4.699             -99999.0                     0.036   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                         0.825                       0.11   
1                         0.763                      0.088   
2                          0.97                      0.095   
3                          0.83                      0.119   
4                         0.941                      0.077   
...                         ...

### 1.8 Seleção Condicional: Filtrando amostras

Durante nossas análise exploratórias, frequentemente filtraremos nossas amostras, a partir de certas **condições**, para fins de análise mais específica. <br/>
Existem algumas maneiras de fazermos tal filtragem. Antes disso, vamos carregar nosso dataset pré-processado que salvamos no item anterior.

In [ ]:
meu_df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                1.288                  0.016                  1.19   
1                1.162                  0.114                  0.89   
2                1.389                  0.097                  1.18   
3                1.262                  0.070                  1.09   
4                1.181                  0.078                  1.05   

   PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                 1.350                0.463                     0.012   
1                 1.449                0.399                     0.098   
2                 1.760                0.419                     0.070   
3                 1.509                0.432                     0.055   
4                 1.400                 0.24                     0.066   

  PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                    0.825                       0.11   
1                    0.763                      0.088   
2                     0.97                      0.095   
3                     0.83                      0.119   
4                    0.941                      0.077   

  PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                    0.4201                    0.9666   
1                    0.5013                      1.05   
2                    0.5614                     1.161   
3                    0.5991                   1.22242   
4                    0.7441                    1.0317   

  COEF DE VARIAÇÃO DISTRIBUIÇÃO  
0                         0.133  
1                         0.115  
2                         0.098  
3                         0.143  
4                         0.082

In [ ]:
meu_df['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

#### **Selecionando apenas os preços dos Postos de São Paulo**

==> Alternativa 1: Seleção Condicional (Comparações diretas)

O código abaixo retorna uma Series ('array') de booleans, com o número de linhas (observações) do Data Frame, que informa os registros de preços dos postos do estado de São Paulo (True).

In [ ]:
meu_df

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
...             ...         ...           ...                 ...   
120818   2021-04-25  2021-05-01         NORTE             RORAIMA   
120819   2021-04-25  2021-05-01           SUL      SANTA CATARINA   
120820   2021-04-25  2021-05-01       SUDESTE           SAO PAULO   
120821   2021-04-25  2021-05-01      NORDESTE             SERGIPE   
120822   2021-04-25  2021-05-01         NORTE           TOCANTINS   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
120818   OLEO DIESEL S10                            12              R$/l   
120819   OLEO DIESEL S10                           100              R$/l   
120820   OLEO DIESEL S10                           886              R$/l   
120821   OLEO DIESEL S10                            33              R$/l   
120822   OLEO DIESEL S10                            18              R$/l   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                     1.288                  0.016                 1.190   
1                     1.162                  0.114                 0.890   
2                     1.389                  0.097                 1.180   
3                     1.262                  0.070                 1.090   
4                     1.181                  0.078                 1.050   
...                     ...                    ...                   ...   
120818                4.582                  0.056                 4.510   
120819                4.141                  0.187                 3.838   
120820                4.246                  0.216                 3.769   
120821                4.464                  0.205                 4.190   
120822                4.352                  0.156                 4.199   

        PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                      1.350                0.463                     0.012   
1                      1.449                0.399                     0.098   
2                      1.760                0.419                     0.070   
3                      1.509                0.432                     0.055   
4                      1.400                 0.24                     0.066   
...                      ...                  ...                       ...   
120818                 4.690             -99999.0                     0.012   
120819                 4.739             -99999.0                     0.045   
120820                 5.199             -99999.0                     0.051   
120821                 4.699             -99999.0                     0.046   
120822                 4.699             -99999.0                     0.036   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                         0.825                       0.11   
1                         0.763                      0.088   
2                          0.97                      0.095   
3                          0.83                      0.119   
4                         0.941                      0.077   
...                         ...

In [ ]:
# faz uma comparação elemento a elemento das series, retornando uma Series de booleans
meu_df['ESTADO'] == 'SAO PAULO'

0         False
1         False
2         False
3         False
4         False
          ...  
120818    False
120819    False
120820     True
120821    False
120822    False
Name: ESTADO, Length: 120823, dtype: bool

In [ ]:
# salvando essa Series de booleans em uma variável
filtro1 = meu_df['ESTADO'] == 'SAO PAULO'

Para filtrarmos os registros de postos do estado de São Paulo:

In [ ]:
meu_df[filtro1]

DATA INICIAL  DATA FINAL   REGIÃO     ESTADO           PRODUTO  \
23       2004-05-09  2004-05-15  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
50       2004-05-16  2004-05-22  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
77       2004-05-23  2004-05-29  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
104      2004-05-30  2004-06-05  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
131      2004-06-06  2004-06-12  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
...             ...         ...      ...        ...               ...   
120723   2021-04-25  2021-05-01  SUDESTE  SAO PAULO    GASOLINA COMUM   
120750   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GLP   
120767   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GNV   
120793   2021-04-25  2021-05-01  SUDESTE  SAO PAULO       OLEO DIESEL   
120820   2021-04-25  2021-05-01  SUDESTE  SAO PAULO   OLEO DIESEL S10   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
23                              4047              R$/l                0.768   
50                              4066              R$/l                0.766   
77                              4077              R$/l                0.823   
104                             4073              R$/l                0.887   
131                             4082              R$/l                0.894   
...                              ...               ...                  ...   
120723                          1187              R$/l                5.265   
120750                           663           R$/13Kg               85.340   
120767                            51             R$/m3                3.150   
120793                           411              R$/l                4.134   
120820                           886              R$/l                4.246   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
23                      0.085                 0.590                 1.150   
50                      0.083                 0.590                 1.150   
77                      0.071                 0.620                 1.199   
104                     0.075                 0.639                 1.359   
131                     0.071                 0.669                 1.199   
...                       ...                   ...                   ...   
120723                  0.218                 4.279                 6.099   
120750                  5.292                68.000                99.990   
120767                  0.282                 2.499                 3.797   
120793                  0.188                 3.699                 5.099   
120820                  0.216                 3.769                 5.199   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
23                    0.198                     0.111   
50                     0.19                     0.108   
77                    0.209                     0.086   
104                   0.216                     0.085   
131                   0.205                     0.079   
...                     ...                       ...   
120723             -99999.0                     0.041   
120750             -99999.0                     0.062   
120767             -99999.0                     0.090   
120793             -99999.0                     0.045   
120820             -99999.0                     0.051   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
23                         0.57                      0.056   
50                        0.576                       0.05   
77                        0.614                      0.063   
104                       0.671                      0.075   
131                       0.689                      0.072   
...                         ...                        ...   
120723                 -99999.0                   -99999.0   
120750                 -99999.0                   -99999.0   
120767       

O resultado é um Data Frame com apenas os registros desejados após a filtragem.
Podemos ainda utilizar o método loc para o mesmo fim:

In [ ]:
meu_df.loc[filtro1]

DATA INICIAL  DATA FINAL   REGIÃO     ESTADO           PRODUTO  \
23       2004-05-09  2004-05-15  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
50       2004-05-16  2004-05-22  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
77       2004-05-23  2004-05-29  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
104      2004-05-30  2004-06-05  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
131      2004-06-06  2004-06-12  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
...             ...         ...      ...        ...               ...   
120723   2021-04-25  2021-05-01  SUDESTE  SAO PAULO    GASOLINA COMUM   
120750   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GLP   
120767   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GNV   
120793   2021-04-25  2021-05-01  SUDESTE  SAO PAULO       OLEO DIESEL   
120820   2021-04-25  2021-05-01  SUDESTE  SAO PAULO   OLEO DIESEL S10   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
23                              4047              R$/l                0.768   
50                              4066              R$/l                0.766   
77                              4077              R$/l                0.823   
104                             4073              R$/l                0.887   
131                             4082              R$/l                0.894   
...                              ...               ...                  ...   
120723                          1187              R$/l                5.265   
120750                           663           R$/13Kg               85.340   
120767                            51             R$/m3                3.150   
120793                           411              R$/l                4.134   
120820                           886              R$/l                4.246   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
23                      0.085                 0.590                 1.150   
50                      0.083                 0.590                 1.150   
77                      0.071                 0.620                 1.199   
104                     0.075                 0.639                 1.359   
131                     0.071                 0.669                 1.199   
...                       ...                   ...                   ...   
120723                  0.218                 4.279                 6.099   
120750                  5.292                68.000                99.990   
120767                  0.282                 2.499                 3.797   
120793                  0.188                 3.699                 5.099   
120820                  0.216                 3.769                 5.199   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
23                    0.198                     0.111   
50                     0.19                     0.108   
77                    0.209                     0.086   
104                   0.216                     0.085   
131                   0.205                     0.079   
...                     ...                       ...   
120723             -99999.0                     0.041   
120750             -99999.0                     0.062   
120767             -99999.0                     0.090   
120793             -99999.0                     0.045   
120820             -99999.0                     0.051   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
23                         0.57                      0.056   
50                        0.576                       0.05   
77                        0.614                      0.063   
104                       0.671                      0.075   
131                       0.689                      0.072   
...                         ...                        ...   
120723                 -99999.0                   -99999.0   
120750                 -99999.0                   -99999.0   
120767       

##### **==> Alternativa 2: Utilizando o método `query`**

`query` filtra linhas de um DataFrame baseado em uma **query (pergunta)**.

In [ ]:
meu_df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                1.288                  0.016                  1.19   
1                1.162                  0.114                  0.89   
2                1.389                  0.097                  1.18   
3                1.262                  0.070                  1.09   
4                1.181                  0.078                  1.05   

   PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                 1.350                0.463                     0.012   
1                 1.449                0.399                     0.098   
2                 1.760                0.419                     0.070   
3                 1.509                0.432                     0.055   
4                 1.400                 0.24                     0.066   

  PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                    0.825                       0.11   
1                    0.763                      0.088   
2                     0.97                      0.095   
3                     0.83                      0.119   
4                    0.941                      0.077   

  PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                    0.4201                    0.9666   
1                    0.5013                      1.05   
2                    0.5614                     1.161   
3                    0.5991                   1.22242   
4                    0.7441                    1.0317   

  COEF DE VARIAÇÃO DISTRIBUIÇÃO  
0                         0.133  
1                         0.115  
2                         0.098  
3                         0.143  
4                         0.082

In [ ]:
meu_df.query('ESTADO == "SAO PAULO"')

DATA INICIAL  DATA FINAL   REGIÃO     ESTADO           PRODUTO  \
23       2004-05-09  2004-05-15  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
50       2004-05-16  2004-05-22  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
77       2004-05-23  2004-05-29  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
104      2004-05-30  2004-06-05  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
131      2004-06-06  2004-06-12  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
...             ...         ...      ...        ...               ...   
120723   2021-04-25  2021-05-01  SUDESTE  SAO PAULO    GASOLINA COMUM   
120750   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GLP   
120767   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GNV   
120793   2021-04-25  2021-05-01  SUDESTE  SAO PAULO       OLEO DIESEL   
120820   2021-04-25  2021-05-01  SUDESTE  SAO PAULO   OLEO DIESEL S10   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
23                              4047              R$/l                0.768   
50                              4066              R$/l                0.766   
77                              4077              R$/l                0.823   
104                             4073              R$/l                0.887   
131                             4082              R$/l                0.894   
...                              ...               ...                  ...   
120723                          1187              R$/l                5.265   
120750                           663           R$/13Kg               85.340   
120767                            51             R$/m3                3.150   
120793                           411              R$/l                4.134   
120820                           886              R$/l                4.246   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
23                      0.085                 0.590                 1.150   
50                      0.083                 0.590                 1.150   
77                      0.071                 0.620                 1.199   
104                     0.075                 0.639                 1.359   
131                     0.071                 0.669                 1.199   
...                       ...                   ...                   ...   
120723                  0.218                 4.279                 6.099   
120750                  5.292                68.000                99.990   
120767                  0.282                 2.499                 3.797   
120793                  0.188                 3.699                 5.099   
120820                  0.216                 3.769                 5.199   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
23                    0.198                     0.111   
50                     0.19                     0.108   
77                    0.209                     0.086   
104                   0.216                     0.085   
131                   0.205                     0.079   
...                     ...                       ...   
120723             -99999.0                     0.041   
120750             -99999.0                     0.062   
120767             -99999.0                     0.090   
120793             -99999.0                     0.045   
120820             -99999.0                     0.051   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
23                         0.57                      0.056   
50                        0.576                       0.05   
77                        0.614                      0.063   
104                       0.671                      0.075   
131                       0.689                      0.072   
...                         ...                        ...   
120723                 -99999.0                   -99999.0   
120750                 -99999.0                   -99999.0   
120767       

<br/>

Uma boa prática é **salvar o Data Frame filtrado em uma nova variável**. Isso simplifica a complexidade do código para futuras análises feitas para os postos de São Paulo (neste caso).

In [ ]:
postos_sp = meu_df.query('ESTADO == "SAO PAULO"')

In [ ]:
postos_sp

DATA INICIAL  DATA FINAL   REGIÃO     ESTADO           PRODUTO  \
23       2004-05-09  2004-05-15  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
50       2004-05-16  2004-05-22  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
77       2004-05-23  2004-05-29  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
104      2004-05-30  2004-06-05  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
131      2004-06-06  2004-06-12  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
...             ...         ...      ...        ...               ...   
120723   2021-04-25  2021-05-01  SUDESTE  SAO PAULO    GASOLINA COMUM   
120750   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GLP   
120767   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GNV   
120793   2021-04-25  2021-05-01  SUDESTE  SAO PAULO       OLEO DIESEL   
120820   2021-04-25  2021-05-01  SUDESTE  SAO PAULO   OLEO DIESEL S10   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
23                              4047              R$/l                0.768   
50                              4066              R$/l                0.766   
77                              4077              R$/l                0.823   
104                             4073              R$/l                0.887   
131                             4082              R$/l                0.894   
...                              ...               ...                  ...   
120723                          1187              R$/l                5.265   
120750                           663           R$/13Kg               85.340   
120767                            51             R$/m3                3.150   
120793                           411              R$/l                4.134   
120820                           886              R$/l                4.246   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
23                      0.085                 0.590                 1.150   
50                      0.083                 0.590                 1.150   
77                      0.071                 0.620                 1.199   
104                     0.075                 0.639                 1.359   
131                     0.071                 0.669                 1.199   
...                       ...                   ...                   ...   
120723                  0.218                 4.279                 6.099   
120750                  5.292                68.000                99.990   
120767                  0.282                 2.499                 3.797   
120793                  0.188                 3.699                 5.099   
120820                  0.216                 3.769                 5.199   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
23                    0.198                     0.111   
50                     0.19                     0.108   
77                    0.209                     0.086   
104                   0.216                     0.085   
131                   0.205                     0.079   
...                     ...                       ...   
120723             -99999.0                     0.041   
120750             -99999.0                     0.062   
120767             -99999.0                     0.090   
120793             -99999.0                     0.045   
120820             -99999.0                     0.051   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
23                         0.57                      0.056   
50                        0.576                       0.05   
77                        0.614                      0.063   
104                       0.671                      0.075   
131                       0.689                      0.072   
...                         ...                        ...   
120723                 -99999.0                   -99999.0   
120750                 -99999.0                   -99999.0   
120767       

In [ ]:
type(postos_sp)

pandas.core.frame.DataFrame

In [ ]:
postos_sp.shape

(4819, 18)

In [ ]:
# Exercício: salvar postos_sp em um arquivo CSV


In [ ]:
postos_sp

DATA INICIAL  DATA FINAL   REGIÃO     ESTADO           PRODUTO  \
23       2004-05-09  2004-05-15  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
50       2004-05-16  2004-05-22  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
77       2004-05-23  2004-05-29  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
104      2004-05-30  2004-06-05  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
131      2004-06-06  2004-06-12  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
...             ...         ...      ...        ...               ...   
120723   2021-04-25  2021-05-01  SUDESTE  SAO PAULO    GASOLINA COMUM   
120750   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GLP   
120767   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GNV   
120793   2021-04-25  2021-05-01  SUDESTE  SAO PAULO       OLEO DIESEL   
120820   2021-04-25  2021-05-01  SUDESTE  SAO PAULO   OLEO DIESEL S10   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
23                              4047              R$/l                0.768   
50                              4066              R$/l                0.766   
77                              4077              R$/l                0.823   
104                             4073              R$/l                0.887   
131                             4082              R$/l                0.894   
...                              ...               ...                  ...   
120723                          1187              R$/l                5.265   
120750                           663           R$/13Kg               85.340   
120767                            51             R$/m3                3.150   
120793                           411              R$/l                4.134   
120820                           886              R$/l                4.246   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
23                      0.085                 0.590                 1.150   
50                      0.083                 0.590                 1.150   
77                      0.071                 0.620                 1.199   
104                     0.075                 0.639                 1.359   
131                     0.071                 0.669                 1.199   
...                       ...                   ...                   ...   
120723                  0.218                 4.279                 6.099   
120750                  5.292                68.000                99.990   
120767                  0.282                 2.499                 3.797   
120793                  0.188                 3.699                 5.099   
120820                  0.216                 3.769                 5.199   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
23                    0.198                     0.111   
50                     0.19                     0.108   
77                    0.209                     0.086   
104                   0.216                     0.085   
131                   0.205                     0.079   
...                     ...                       ...   
120723             -99999.0                     0.041   
120750             -99999.0                     0.062   
120767             -99999.0                     0.090   
120793             -99999.0                     0.045   
120820             -99999.0                     0.051   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
23                         0.57                      0.056   
50                        0.576                       0.05   
77                        0.614                      0.063   
104                       0.671                      0.075   
131                       0.689                      0.072   
...                         ...                        ...   
120723                 -99999.0                   -99999.0   
120750                 -99999.0                   -99999.0   
120767       

#### Resetando os índices

Note que os _índices das linhas/registros_ após a _filtragem_ **continuam sendo os mesmos** do DataFrame original. <br/>
Em muitas situações, manter esta informação será importante.

Mas, se você quiser **_resetar os índices_** do data frame filtrado, fazendo com que os registros começem com _índice 0 até num_linhas-1_, use o método `.reset_index`.

In [ ]:
postos_sp.reset_index()

index DATA INICIAL  DATA FINAL   REGIÃO     ESTADO           PRODUTO  \
0         23   2004-05-09  2004-05-15  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
1         50   2004-05-16  2004-05-22  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
2         77   2004-05-23  2004-05-29  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
3        104   2004-05-30  2004-06-05  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
4        131   2004-06-06  2004-06-12  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
...      ...          ...         ...      ...        ...               ...   
4814  120723   2021-04-25  2021-05-01  SUDESTE  SAO PAULO    GASOLINA COMUM   
4815  120750   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GLP   
4816  120767   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GNV   
4817  120793   2021-04-25  2021-05-01  SUDESTE  SAO PAULO       OLEO DIESEL   
4818  120820   2021-04-25  2021-05-01  SUDESTE  SAO PAULO   OLEO DIESEL S10   

      NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
0                             4047              R$/l                0.768   
1                             4066              R$/l                0.766   
2                             4077              R$/l                0.823   
3                             4073              R$/l                0.887   
4                             4082              R$/l                0.894   
...                            ...               ...                  ...   
4814                          1187              R$/l                5.265   
4815                           663           R$/13Kg               85.340   
4816                            51             R$/m3                3.150   
4817                           411              R$/l                4.134   
4818                           886              R$/l                4.246   

      DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
0                     0.085                 0.590                 1.150   
1                     0.083                 0.590                 1.150   
2                     0.071                 0.620                 1.199   
3                     0.075                 0.639                 1.359   
4                     0.071                 0.669                 1.199   
...                     ...                   ...                   ...   
4814                  0.218                 4.279                 6.099   
4815                  5.292                68.000                99.990   
4816                  0.282                 2.499                 3.797   
4817                  0.188                 3.699                 5.099   
4818                  0.216                 3.769                 5.199   

     MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA PREÇO MÉDIO DISTRIBUIÇÃO  \
0                   0.198                     0.111                     0.57   
1                    0.19                     0.108                    0.576   
2                   0.209                     0.086                    0.614   
3                   0.216                     0.085                    0.671   
4                   0.205                     0.079                    0.689   
...                   ...                       ...                      ...   
4814             -99999.0                     0.041                 -99999.0   
4815             -99999.0                     0.062                 -99999.0   
4816             -99999.0                     0.090                 -99999.0   
4817             -99999.0                     0.045                 -99999.0   
4818             -99999.0                     0.051                 -99999.0   

     DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                         0.056                    0.4271   
1                          0.05                   0.43204   
2                         0.063                   0.34951   
3                         0

In [ ]:
postos_sp

DATA INICIAL  DATA FINAL   REGIÃO     ESTADO           PRODUTO  \
23       2004-05-09  2004-05-15  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
50       2004-05-16  2004-05-22  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
77       2004-05-23  2004-05-29  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
104      2004-05-30  2004-06-05  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
131      2004-06-06  2004-06-12  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
...             ...         ...      ...        ...               ...   
120723   2021-04-25  2021-05-01  SUDESTE  SAO PAULO    GASOLINA COMUM   
120750   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GLP   
120767   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GNV   
120793   2021-04-25  2021-05-01  SUDESTE  SAO PAULO       OLEO DIESEL   
120820   2021-04-25  2021-05-01  SUDESTE  SAO PAULO   OLEO DIESEL S10   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
23                              4047              R$/l                0.768   
50                              4066              R$/l                0.766   
77                              4077              R$/l                0.823   
104                             4073              R$/l                0.887   
131                             4082              R$/l                0.894   
...                              ...               ...                  ...   
120723                          1187              R$/l                5.265   
120750                           663           R$/13Kg               85.340   
120767                            51             R$/m3                3.150   
120793                           411              R$/l                4.134   
120820                           886              R$/l                4.246   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
23                      0.085                 0.590                 1.150   
50                      0.083                 0.590                 1.150   
77                      0.071                 0.620                 1.199   
104                     0.075                 0.639                 1.359   
131                     0.071                 0.669                 1.199   
...                       ...                   ...                   ...   
120723                  0.218                 4.279                 6.099   
120750                  5.292                68.000                99.990   
120767                  0.282                 2.499                 3.797   
120793                  0.188                 3.699                 5.099   
120820                  0.216                 3.769                 5.199   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
23                    0.198                     0.111   
50                     0.19                     0.108   
77                    0.209                     0.086   
104                   0.216                     0.085   
131                   0.205                     0.079   
...                     ...                       ...   
120723             -99999.0                     0.041   
120750             -99999.0                     0.062   
120767             -99999.0                     0.090   
120793             -99999.0                     0.045   
120820             -99999.0                     0.051   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
23                         0.57                      0.056   
50                        0.576                       0.05   
77                        0.614                      0.063   
104                       0.671                      0.075   
131                       0.689                      0.072   
...                         ...                        ...   
120723                 -99999.0                   -99999.0   
120750                 -99999.0                   -99999.0   
120767       

In [ ]:
postos_sp.reset_index(drop=True, inplace=True)

In [ ]:
postos_sp

DATA INICIAL  DATA FINAL   REGIÃO     ESTADO           PRODUTO  \
0      2004-05-09  2004-05-15  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
1      2004-05-16  2004-05-22  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
2      2004-05-23  2004-05-29  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
3      2004-05-30  2004-06-05  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
4      2004-06-06  2004-06-12  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
...           ...         ...      ...        ...               ...   
4814   2021-04-25  2021-05-01  SUDESTE  SAO PAULO    GASOLINA COMUM   
4815   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GLP   
4816   2021-04-25  2021-05-01  SUDESTE  SAO PAULO               GNV   
4817   2021-04-25  2021-05-01  SUDESTE  SAO PAULO       OLEO DIESEL   
4818   2021-04-25  2021-05-01  SUDESTE  SAO PAULO   OLEO DIESEL S10   

      NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
0                             4047              R$/l                0.768   
1                             4066              R$/l                0.766   
2                             4077              R$/l                0.823   
3                             4073              R$/l                0.887   
4                             4082              R$/l                0.894   
...                            ...               ...                  ...   
4814                          1187              R$/l                5.265   
4815                           663           R$/13Kg               85.340   
4816                            51             R$/m3                3.150   
4817                           411              R$/l                4.134   
4818                           886              R$/l                4.246   

      DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
0                     0.085                 0.590                 1.150   
1                     0.083                 0.590                 1.150   
2                     0.071                 0.620                 1.199   
3                     0.075                 0.639                 1.359   
4                     0.071                 0.669                 1.199   
...                     ...                   ...                   ...   
4814                  0.218                 4.279                 6.099   
4815                  5.292                68.000                99.990   
4816                  0.282                 2.499                 3.797   
4817                  0.188                 3.699                 5.099   
4818                  0.216                 3.769                 5.199   

     MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA PREÇO MÉDIO DISTRIBUIÇÃO  \
0                   0.198                     0.111                     0.57   
1                    0.19                     0.108                    0.576   
2                   0.209                     0.086                    0.614   
3                   0.216                     0.085                    0.671   
4                   0.205                     0.079                    0.689   
...                   ...                       ...                      ...   
4814             -99999.0                     0.041                 -99999.0   
4815             -99999.0                     0.062                 -99999.0   
4816             -99999.0                     0.090                 -99999.0   
4817             -99999.0                     0.045                 -99999.0   
4818             -99999.0                     0.051                 -99999.0   

     DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                         0.056                    0.4271   
1                          0.05                   0.43204   
2                         0.063                   0.34951   
3                         0.075                    0.3398   
4                         0.072                   0.47797   

#### **Selecionando registros de postos do Rio de Janeiro com Preços acima de 2 reais**

In [ ]:
filtro2 = (meu_df['ESTADO'] == 'RIO DE JANEIRO') & (meu_df['PREÇO MÉDIO REVENDA'] > 2)
filtro2

0         False
1         False
2         False
3         False
4         False
          ...  
120818    False
120819    False
120820    False
120821    False
120822    False
Length: 120823, dtype: bool

In [ ]:
meu_df[filtro2]

DATA INICIAL  DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
2501     2006-02-26  2006-03-04  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
2528     2006-03-05  2006-03-11  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
2555     2006-03-12  2006-03-18  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
2582     2006-03-19  2006-03-25  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
2609     2006-03-26  2006-04-01  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
...             ...         ...      ...             ...               ...   
120717   2021-04-25  2021-05-01  SUDESTE  RIO DE JANEIRO    GASOLINA COMUM   
120744   2021-04-25  2021-05-01  SUDESTE  RIO DE JANEIRO               GLP   
120763   2021-04-25  2021-05-01  SUDESTE  RIO DE JANEIRO               GNV   
120787   2021-04-25  2021-05-01  SUDESTE  RIO DE JANEIRO       OLEO DIESEL   
120814   2021-04-25  2021-05-01  SUDESTE  RIO DE JANEIRO   OLEO DIESEL S10   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
2501                             881              R$/l                2.028   
2528                             889              R$/l                2.125   
2555                             902              R$/l                2.163   
2582                             898              R$/l                2.166   
2609                             890              R$/l                2.172   
...                              ...               ...                  ...   
120717                           198              R$/l                6.099   
120744                           137           R$/13Kg               75.218   
120763                            77             R$/m3                3.011   
120787                            72              R$/l                4.290   
120814                           155              R$/l                4.302   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
2501                    0.148                 1.589                 2.550   
2528                    0.149                 1.779                 2.550   
2555                    0.138                 1.799                 2.599   
2582                    0.146                 1.760                 2.568   
2609                    0.143                 1.789                 2.550   
...                       ...                   ...                   ...   
120717                  0.208                 5.480                 6.599   
120744                  5.398                65.000                93.000   
120763                  0.385                 2.759                 4.399   
120787                  0.183                 3.849                 4.599   
120814                  0.172                 3.930                 4.699   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
2501                  0.222                     0.073   
2528                  0.286                     0.070   
2555                  0.268                     0.064   
2582                  0.231                     0.067   
2609                  0.209                     0.066   
...                     ...                       ...   
120717             -99999.0                     0.034   
120744             -99999.0                     0.072   
120763             -99999.0                     0.128   
120787             -99999.0                     0.043   
120814             -99999.0                     0.040   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
2501                      1.806                       0.11   
2528                      1.839                      0.117   
2555                      1.895                      0.134   
2582                      1.935                       0.14   
2609                      1.963                      0.133   
...                         ...                        ...   
120717                 -99999.0                   -99999.0   
120744         

Note que o resultado da seleção continua sendo uma _Series de booleans_ com o _mesmo número de linhas/observações do DataFrame_, de modo que cada linha possuirá um valor booleano indicando se o posto é do Rio de Janeiro **E** o preço aferido do combustível é maior que 2 reais (True) ou não.

O símbolo **&** significa **AND** na comparação. Essa nomenclatura do python/pandas é diferente das nomenclaturas tradicionais (&&). <br/>
Similarmente:
- **|** representa o **OR** (não é ||)
- **~** representa o **NOT** (não é !)

Alternativamente, poderíamos usar o método `query` para fazermos tal seleção. Porém, isso não é possível especificamente para esse caso, pois o rótulo da coluna 'PREÇO MÉDIO REVENDA' possui caracteres inválidos para o método (espaço, cedilha, acentos).

In [ ]:
# Não funciona
#data.query('ESTADO=="RIO DE JANEIRO" and PREÇO MÉDIO REVENDA > 2')

In [ ]:
#meu_df.query('ESTADO == "RIO DE JANEIRO" or ESTADO == "SAO PAULO"')

In [ ]:
meu_df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                1.288                  0.016                  1.19   
1                1.162                  0.114                  0.89   
2                1.389                  0.097                  1.18   
3                1.262                  0.070                  1.09   
4                1.181                  0.078                  1.05   

   PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                 1.350                0.463                     0.012   
1                 1.449                0.399                     0.098   
2                 1.760                0.419                     0.070   
3                 1.509                0.432                     0.055   
4                 1.400                 0.24                     0.066   

  PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                    0.825                       0.11   
1                    0.763                      0.088   
2                     0.97                      0.095   
3                     0.83                      0.119   
4                    0.941                      0.077   

  PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                    0.4201                    0.9666   
1                    0.5013                      1.05   
2                    0.5614                     1.161   
3                    0.5991                   1.22242   
4                    0.7441                    1.0317   

  COEF DE VARIAÇÃO DISTRIBUIÇÃO  
0                         0.133  
1                         0.115  
2                         0.098  
3                         0.143  
4                         0.082

## Exercício (Valendo Presença - 29/03/2025)
Crie um novo notebook e salve com o seu nome (ex: joao_silva.ipynb). Em seguida, realize os itens abaixo com base no dataset 2004-2021.tsv.

**a.** Quais são os nomes dos estados presentes no DataFrame? Dica: Veja a seção 1.8

**b.** Quais tipos de combustíveis estão presentes no DataFrame?

**c.** Você percebeu algum tipo de problema nos valores encontrados nos itens (a) e (b)?

**d.** Selecione os registros de postos de São Paulo ou Santa Catarina com preço médio de revenda do Etanol acima de R$2,15.

**e.** Quantos registros existem na seleção realizada no item (d)?

**f.** Salve os registro do item anterior em um arquivo CSV com o nome **minha_pesquisa**. Dica: Veja seção 1.7

**g.** Envie seu arquivo .ipynb no Moodle até o final da aula.




## 2. Limpeza dos dados

In [ ]:
df = pd.read_csv('/content/2004-2021.tsv', sep='\t')

In [ ]:
df.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                1.288                  0.016                  1.19   
1                1.162                  0.114                  0.89   
2                1.389                  0.097                  1.18   
3                1.262                  0.070                  1.09   
4                1.181                  0.078                  1.05   

   PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                 1.350                0.463                     0.012   
1                 1.449                0.399                     0.098   
2                 1.760                0.419                     0.070   
3                 1.509                0.432                     0.055   
4                 1.400                 0.24                     0.066   

  PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                    0.825                       0.11   
1                    0.763                      0.088   
2                     0.97                      0.095   
3                     0.83                      0.119   
4                    0.941                      0.077   

  PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                    0.4201                    0.9666   
1                    0.5013                      1.05   
2                    0.5614                     1.161   
3                    0.5991                   1.22242   
4                    0.7441                    1.0317   

  COEF DE VARIAÇÃO DISTRIBUIÇÃO  
0                         0.133  
1                         0.115  
2                         0.098  
3                         0.143  
4                         0.082

### 2.1 Tratando observações com valores vazios (null / nan) no dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   DATA INICIAL                   120823 non-null  object 
 1   DATA FINAL                     120823 non-null  object 
 2   REGIÃO                         120823 non-null  object 
 3   ESTADO                         120823 non-null  object 
 4   PRODUTO                        120823 non-null  object 
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64  
 6   UNIDADE DE MEDIDA              120823 non-null  object 
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  object 
 12  COEF DE VARIAÇÃO REVENDA      

De um total de 120823 observações, **não há valores null / nan** para nenhum atributo. Mas, veremos que não é bem assim neste caso específico.<br/><br/>

### 2.2 Conversão de tipos de atributos

O pandas automaticamente reconhece os tipos de dados de cada coluna. <br/>
Porém, existem alguns atributos que estão com seus tipos errados: Por exemplo: "PREÇO MÉDIO DISTRIBUIÇÃO" deveria ser ```float64``` e não ```object```.<br/>
Nestes casos, muito provavelmente alguns registros têm uma string ao invés de um número para tais atributos. <br/>

Os atributos **"DATA INICIAL"** e **"DATA FINAL"** deveriam ser do tipo `datetime`.

In [ ]:
data_pre = df.copy()

#### **Datas**
Como os atributos de data do dataset já estão em um formato de data aceitável (YYYY-MM-DD), não precisamos forçar nenhuma conversão nesse sentido.

In [ ]:
data_pre['DATA INICIAL'] = pd.to_datetime(data_pre['DATA INICIAL'])
data_pre['DATA FINAL'] = pd.to_datetime(data_pre['DATA FINAL'])

In [ ]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   DATA INICIAL                   120823 non-null  datetime64[ns]
 1   DATA FINAL                     120823 non-null  datetime64[ns]
 2   REGIÃO                         120823 non-null  object        
 3   ESTADO                         120823 non-null  object        
 4   PRODUTO                        120823 non-null  object        
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64         
 6   UNIDADE DE MEDIDA              120823 non-null  object        
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64       
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64       
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64       
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64       
 11  

#### **Dados Numéricos**

In [ ]:
# convertendo atributos/colunas para 'numeric'
# https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html
lista = ['MARGEM MÉDIA REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO', 'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO']
for atributo in lista:
    #print(atributo)
    # converte a coluna (de valores string) para um tipo numérico
    # Em caso de erro na conversão (p. ex., uma string que não representa um número), um valor vazio (null / nan) será
    # atribuído no lugar
   data_pre[atributo] = pd.to_numeric(data_pre[atributo], errors='coerce')

In [ ]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   DATA INICIAL                   120823 non-null  datetime64[ns]
 1   DATA FINAL                     120823 non-null  datetime64[ns]
 2   REGIÃO                         120823 non-null  object        
 3   ESTADO                         120823 non-null  object        
 4   PRODUTO                        120823 non-null  object        
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64         
 6   UNIDADE DE MEDIDA              120823 non-null  object        
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64       
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64       
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64       
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64       
 11  

Note que temos vários valores ***null*** agora **após a *conversão de tipos***. Vamos checá-los com mais cuidado nos dados originais e preprocessados.

### 2.3 Limpeza de dados

In [ ]:
mask = data_pre['DESVIO PADRÃO DISTRIBUIÇÃO'].isnull()

In [ ]:
data_pre[mask]

DATA INICIAL DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
1903     2005-09-25 2005-10-01    NORTE            PARA  ETANOL HIDRATADO   
1958     2005-10-09 2005-10-15    NORTE         RORAIMA  ETANOL HIDRATADO   
2012     2005-10-23 2005-10-29    NORTE         RORAIMA  ETANOL HIDRATADO   
2497     2006-02-26 2006-03-04    NORTE         RORAIMA  ETANOL HIDRATADO   
3199     2006-08-27 2006-09-02    NORTE         RORAIMA  ETANOL HIDRATADO   
...             ...        ...      ...             ...               ...   
106664   2019-06-16 2019-06-22  SUDESTE    MINAS GERAIS               GNV   
106666   2019-06-16 2019-06-22      SUL          PARANA               GNV   
106811   2019-06-23 2019-06-29  SUDESTE  ESPIRITO SANTO               GNV   
106813   2019-06-23 2019-06-29  SUDESTE    MINAS GERAIS               GNV   
106815   2019-06-23 2019-06-29      SUL          PARANA               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
1903                               2              R$/l                1.694   
1958                               3              R$/l                2.000   
2012                               3              R$/l                2.277   
2497                              11              R$/l                2.182   
3199                              22              R$/l                2.285   
...                              ...               ...                  ...   
106664                             5             R$/m3                3.445   
106666                             7             R$/m3                3.132   
106811                             4             R$/m3                3.299   
106813                             6             R$/m3                3.548   
106815                             1             R$/m3                3.290   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
1903                    0.283                 1.690                 2.090   
1958                    0.000                 2.000                 2.000   
2012                    0.023                 2.250                 2.290   
2497                    0.040                 2.100                 2.200   
3199                    0.068                 1.980                 2.300   
...                       ...                   ...                   ...   
106664                  0.147                 3.347                 3.699   
106666                  0.295                 3.049                 3.890   
106811                  0.005                 3.290                 3.299   
106813                  0.100                 3.495                 3.699   
106815                  0.000                 3.290                 3.290   

        MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
1903                     NaN                     0.167   
1958                     NaN                     0.000   
2012                     NaN                     0.010   
2497                     NaN                     0.018   
3199                     NaN                     0.030   
...                      ...                       ...   
106664                   NaN                     0.043   
106666                   NaN                     0.094   
106811                   NaN                     0.002   
106813                   NaN                     0.028   
106815                   NaN                     0.000   

        PREÇO MÉDIO DISTRIBUIÇÃO  DESVIO PADRÃO DISTRIBUIÇÃO  \
1903                         NaN                         NaN   
1958                         NaN                         NaN   
2012                         NaN                         NaN   
2497                         NaN                         NaN   
3199                         NaN                         NaN   
...                          ...                         ...   
106664                       NaN                         NaN   

In [ ]:
# Nos dados originais, quais eram os valores do PREÇO MÉDIO DISTRIBUIÇÃO dos registros que agora possuem valores NaN
df[mask]

DATA INICIAL  DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
1903     2005-09-25  2005-10-01    NORTE            PARA  ETANOL HIDRATADO   
1958     2005-10-09  2005-10-15    NORTE         RORAIMA  ETANOL HIDRATADO   
2012     2005-10-23  2005-10-29    NORTE         RORAIMA  ETANOL HIDRATADO   
2497     2006-02-26  2006-03-04    NORTE         RORAIMA  ETANOL HIDRATADO   
3199     2006-08-27  2006-09-02    NORTE         RORAIMA  ETANOL HIDRATADO   
...             ...         ...      ...             ...               ...   
106664   2019-06-16  2019-06-22  SUDESTE    MINAS GERAIS               GNV   
106666   2019-06-16  2019-06-22      SUL          PARANA               GNV   
106811   2019-06-23  2019-06-29  SUDESTE  ESPIRITO SANTO               GNV   
106813   2019-06-23  2019-06-29  SUDESTE    MINAS GERAIS               GNV   
106815   2019-06-23  2019-06-29      SUL          PARANA               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
1903                               2              R$/l                1.694   
1958                               3              R$/l                2.000   
2012                               3              R$/l                2.277   
2497                              11              R$/l                2.182   
3199                              22              R$/l                2.285   
...                              ...               ...                  ...   
106664                             5             R$/m3                3.445   
106666                             7             R$/m3                3.132   
106811                             4             R$/m3                3.299   
106813                             6             R$/m3                3.548   
106815                             1             R$/m3                3.290   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
1903                    0.283                 1.690                 2.090   
1958                    0.000                 2.000                 2.000   
2012                    0.023                 2.250                 2.290   
2497                    0.040                 2.100                 2.200   
3199                    0.068                 1.980                 2.300   
...                       ...                   ...                   ...   
106664                  0.147                 3.347                 3.699   
106666                  0.295                 3.049                 3.890   
106811                  0.005                 3.290                 3.299   
106813                  0.100                 3.495                 3.699   
106815                  0.000                 3.290                 3.290   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
1903                      -                     0.167   
1958                      -                     0.000   
2012                      -                     0.010   
2497                      -                     0.018   
3199                      -                     0.030   
...                     ...                       ...   
106664                    -                     0.043   
106666                    -                     0.094   
106811                    -                     0.002   
106813                    -                     0.028   
106815                    -                     0.000   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
1903                          -                          -   
1958                          -                          -   
2012                          -                          -   
2497                          -                          -   
3199                          -                          -   
...                         ...                        ...   
106664                        -                          -   
106666         

Várias amostras possuem a _string '-'_ em algumas colunas ao invés de um número de fato. Ou seja, não há aferições destes atributos para estas amostras. <br/>

<br/>

Poderíamos **preencher os valores NaN com um valor padrão**. Para isso, basta usar o método `.fillna`.

In [ ]:
# Retorna uma cópia do data frame `data_pre` com todos os valores NaN de todas as colunas agora preenchidos com 0.
data_pre_fill = data_pre.fillna(0)

In [ ]:
# valores que antes eram NaN, agora são 0
data_pre_fill[mask]

DATA INICIAL DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
1903     2005-09-25 2005-10-01    NORTE            PARA  ETANOL HIDRATADO   
1958     2005-10-09 2005-10-15    NORTE         RORAIMA  ETANOL HIDRATADO   
2012     2005-10-23 2005-10-29    NORTE         RORAIMA  ETANOL HIDRATADO   
2497     2006-02-26 2006-03-04    NORTE         RORAIMA  ETANOL HIDRATADO   
3199     2006-08-27 2006-09-02    NORTE         RORAIMA  ETANOL HIDRATADO   
...             ...        ...      ...             ...               ...   
106664   2019-06-16 2019-06-22  SUDESTE    MINAS GERAIS               GNV   
106666   2019-06-16 2019-06-22      SUL          PARANA               GNV   
106811   2019-06-23 2019-06-29  SUDESTE  ESPIRITO SANTO               GNV   
106813   2019-06-23 2019-06-29  SUDESTE    MINAS GERAIS               GNV   
106815   2019-06-23 2019-06-29      SUL          PARANA               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
1903                               2              R$/l                1.694   
1958                               3              R$/l                2.000   
2012                               3              R$/l                2.277   
2497                              11              R$/l                2.182   
3199                              22              R$/l                2.285   
...                              ...               ...                  ...   
106664                             5             R$/m3                3.445   
106666                             7             R$/m3                3.132   
106811                             4             R$/m3                3.299   
106813                             6             R$/m3                3.548   
106815                             1             R$/m3                3.290   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
1903                    0.283                 1.690                 2.090   
1958                    0.000                 2.000                 2.000   
2012                    0.023                 2.250                 2.290   
2497                    0.040                 2.100                 2.200   
3199                    0.068                 1.980                 2.300   
...                       ...                   ...                   ...   
106664                  0.147                 3.347                 3.699   
106666                  0.295                 3.049                 3.890   
106811                  0.005                 3.290                 3.299   
106813                  0.100                 3.495                 3.699   
106815                  0.000                 3.290                 3.290   

        MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
1903                     0.0                     0.167   
1958                     0.0                     0.000   
2012                     0.0                     0.010   
2497                     0.0                     0.018   
3199                     0.0                     0.030   
...                      ...                       ...   
106664                   0.0                     0.043   
106666                   0.0                     0.094   
106811                   0.0                     0.002   
106813                   0.0                     0.028   
106815                   0.0                     0.000   

        PREÇO MÉDIO DISTRIBUIÇÃO  DESVIO PADRÃO DISTRIBUIÇÃO  \
1903                         0.0                         0.0   
1958                         0.0                         0.0   
2012                         0.0                         0.0   
2497                         0.0                         0.0   
3199                         0.0                         0.0   
...                          ...                         ...   
106664                       0.0                         0.0   

In [ ]:
data_pre_fill.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   DATA INICIAL                   120823 non-null  datetime64[ns]
 1   DATA FINAL                     120823 non-null  datetime64[ns]
 2   REGIÃO                         120823 non-null  object        
 3   ESTADO                         120823 non-null  object        
 4   PRODUTO                        120823 non-null  object        
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64         
 6   UNIDADE DE MEDIDA              120823 non-null  object        
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64       
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64       
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64       
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64       
 11  

Por mais que a função `fillna` seja interessante e útil em muitos casos, no problema em questão estamos interessados em analisar precisamente, p. ex., o **'PREÇO MÉDIO REVENDA'**.<br/>
A fim de não termos valores _sintéticos_ gerados pelo `fillna`, que possam atrapalhar nossa análise, iremos **remover (drop) todas as amostras que possuem qualquer valor NaN** para quaisquer atributos/colunas. <br/>

Para isso, basta utilizarmos o método `dropna`.

In [ ]:
# remove, no próprio dataframe, todas as linhas/registros com valores NaN (vazios) em quaisquer colunas/atributos.
data_pre.dropna(inplace=True)

In [ ]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
Index: 117392 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   DATA INICIAL                   117392 non-null  datetime64[ns]
 1   DATA FINAL                     117392 non-null  datetime64[ns]
 2   REGIÃO                         117392 non-null  object        
 3   ESTADO                         117392 non-null  object        
 4   PRODUTO                        117392 non-null  object        
 5   NÚMERO DE POSTOS PESQUISADOS   117392 non-null  int64         
 6   UNIDADE DE MEDIDA              117392 non-null  object        
 7   PREÇO MÉDIO REVENDA            117392 non-null  float64       
 8   DESVIO PADRÃO REVENDA          117392 non-null  float64       
 9   PREÇO MÍNIMO REVENDA           117392 non-null  float64       
 10  PREÇO MÁXIMO REVENDA           117392 non-null  float64       
 11  MARGE

Nosso data frame agora, após essa _limpeza_, ficou mais enxuto, contentdo 117392 registros frente aos 120823 registros originais. <br/>

Essas são apenas algumas das possíveis _técnicas de limpeza de dados_. Outras estratégias mais sofisticadas não veremos neste curso.

#### **Salvando o Dataset Preprocessado**

In [ ]:
data_pre.to_csv('2004-2021_preprocessado_final.csv', index=False)

# 📝 Exercício (Valendo Presença – 12/04/2025)

Crie um novo notebook no Google Colab (ou Jupyter) e salve com **seu nome e a data** no nome do arquivo, seguindo o modelo:  
`seu_nome_12_abril.ipynb`  
*(exemplo: `joao_silva_12_abril.ipynb`)*

Em seguida, realize os itens abaixo utilizando o dataset **2004-2021.tsv**.

---

## a. Importação
Importe o arquivo **2004-2021.tsv** e salve-o em um DataFrame chamado `df`.  
**Dica**: Veja a seção 1.1 sobre importação de dados com separador TAB.

---

## b. Estados presentes
Quais são os nomes dos estados presentes no DataFrame?  
**Dica**: Veja a seção 1.8 sobre valores únicos.

---

## c. Filtragem por estado
Escolha um estado e crie um novo DataFrame apenas com os registros desse estado.  
Dê a esse DataFrame um nome apropriado, como `df_RJ` se você escolher o Rio de Janeiro.  
**Dica**: Veja a seção 1.8 sobre filtragem de dados.

---

## d. Contagem de registros
Quantas linhas existem no DataFrame criado no item (c)?

---

## e. Conversão de datas
Converta as colunas **"DATA INICIAL"** e **"DATA FINAL"** para o tipo `datetime`.  
**Dica**: Veja a seção 2.2 sobre conversão de datas.

---

## f. Conversão numérica
Converta para tipo numérico as colunas que representam preços, como:  
`PREÇO MÉDIO`, `PREÇO MÍNIMO`, `PREÇO MÁXIMO`, `PREÇO DE VENDA`, entre outras.  
**Dica**: Veja a seção 2.2 sobre conversão de tipos.

---

## g. Valores ausentes
Após a conversão, quantos valores ausentes (**null/NaN**) existem no DataFrame?

---

## h. Remoção de linhas com NaN
Elimine todas as linhas que contenham **valores ausentes (null/NaN)** em qualquer coluna.  
**Dica**: Veja a seção 2.3 sobre remoção de dados faltantes.

---

## i. Exportação do resultado
Salve o DataFrame final do item (h) em um novo arquivo CSV chamado:  
`minha_pesquisa_12_abril.csv`  
**Dica**: Veja a seção 1.7 sobre exportação de arquivos.

---

## j. Entrega
Envie o arquivo `.ipynb` (do notebook) no Moodle até o final da aula.

<h2>3. Estatísticas Descritivas</h2>
<hr/>

In [ ]:
data_final = pd.read_csv('/content/2004-2021_preprocessado_final.csv')

In [ ]:
data_final.head()

O Pandas fornecem algumas funções/métodos que computam certas estatísticas descritivas.

`describe`: exibe várias **estatísticas descritivas** para os _atributos_ de um dataframe ou para uma _Series_.

<br/>

Como o resultado do `describe` de um _dataframe_ é outro _dataframe_, podemos filtrar apenas algumas colunas.

**Acessando apenas algumas estatísticas**

<br/>

`mean`, `std`, `min`, etc: cada uma das estatísticas do `describe` podem ser computadas individualmente:

#### Qual é o menor preço mínimo de revenda?

#### Qual é a média e desvio padrão dos preços mínimos de revenda?

#### Quais são os estados considerados?

#### Quantos registros (aferições) cada estado possui?

`.value_counts()`:  Conta a frequência dos valores de uma dada variável (de preferência, _categórica_).